[dlg Title_Camera]
Camera[w][e]

[sel Options_Camera]
Reposition Camera[f 4 26 0 3][e]
Adjust FOV[f 4 26 1 4][e]
Adjust Zoom[f 4 26 2 5][e]
Rotate Camera[f 4 26 3 6][e]
Unlock Camera[f 4 26 4 7][e]
Lock Camera[f 4 26 5 8][e]
Disable Camera Shake[f 4 26 6 9][e]

[dlg GENERIC_HELP_2]
Move the camera along the X, Y[n]or Z axis. Hold [clr 18]□[clr 0] to change
[n]the axis.[e]

[dlg GENERIC_HELP_3]
Adjust the camera's[n]Field of View.[e]

[dlg GENERIC_HELP_4]
Zoom the camera in[n] and out.[e]

[dlg GENERIC_HELP_5]
Change the orientation of the[n] camera with the D-pad.[e]

[dlg GENERIC_HELP_6]
 Make the camera follow the player[n] again if previously locked.[e]

[dlg GENERIC_HELP_7]
Makes the camera stationary, [n] which is required to modify it.[e]

[dlg Message_Camera]
Use the D-Pad to manipulate the camera.
[n]Press [clr 4]△[clr 0] to quit.[w][e]