[msg Camera]
[w][e]

[dlg Title_Camera]
Camera[w][e]

[sel Options_Camera]
Reposition Camera[ref 0 3][e]
Adjust FOV[ref 1 4][e]
Adjust Zoom[ref 2 5][e]
Rotate Camera[ref 3 6][e]
Unlock Camera[ref 4 7][e]
Lock Camera[ref 5 8][e]
Disable Camera Shake[ref 6 9][e]

[dlg GENERIC_HELP_2]
Move the camera along the X, Y
[n]or Z axis. Hold [clr 18]IM button[clr 0] to
[n]change the axis.
[n](Requires controller)//Royal
[e]

[dlg GENERIC_HELP_3]
Adjust the camera's
[n]Field of View. [clr 9]WARNING:
[n]Controller only or softlock![clr 0][e]

[dlg GENERIC_HELP_4]
Zoom the camera in
[n]and out. [clr 9]WARNING:
[n]Controller only or softlock![clr 0][e]

[dlg GENERIC_HELP_5]
Change the orientation of the
[n]camera with the D-pad.
[n][clr 9]WARNING: Controller
[n]only or softlock![clr 0][e]

[dlg GENERIC_HELP_6]
Make the camera follow the player
[n]again if previously locked.[e]

[dlg GENERIC_HELP_7]
Makes the camera stationary,
[n]which is required to modify it.[e]

[dlg Message_Camera]
Use the D-Pad to manipulate the camera.
[n]([clr 4]menu button[clr 0] to quit.)[w][e]