[dlg Title_FlagCategories]
Flag Categories[w][e]

[sel Options_FlagCategories]
HUD Flags[f 4 26 0 2][e]
Party Flags[f 4 26 1 3][e]
Persona Flags[f 4 26 2 4][e]
Room Flags[f 4 26 3 5][e]

[dlg GENERIC_HELP_2]
[s]Choose flags to toggle that[n]are related to the[n]user interface.[e]

[dlg GENERIC_HELP_3]
[s]Choose flags to toggle[n]that are related to[n]party members.[e]

[dlg GENERIC_HELP_4]
[s]RChoose flags to toggle[n]that are related to[n]Personas.[e]

[dlg GENERIC_HELP_5]
[s]RChoose flags to toggle[n]that are related to[n]the protag's bedroom.[e]