[dlg ModMenuName]
Amicitia Mod Menu[w][e]

[sel ModMenu]
[s]Player[f 4 26 0 93][e]
[s]Battle Select[f 4 26 1 94][e]
[s]Teleport[f 4 26 2 95][e]
[s]Sound Test[f 4 26 3 96][e]
[s]Field Select[f 4 26 4 97][e]
[s]Event Select[f 4 26 5 98][e]
[s]Camera[f 4 26 6 99][e]
[s]NPCs[f 4 26 7 100][e]
[s]Flags[f 4 26 8 101][e]
[s]Calendar[f 4 26 9 102][e]
[s]Cutin Test[f 4 26 10 103][e]
[s]Font Test[f 4 26 11 104][e]
[s]Check Phone/Auto Recover[f 4 26 12 105][e]
[s]About[f 4 26 13 106][e]

[dlg GENERIC_HELP_93]
[s]Edit your Personas, items, stats,[n]money, or even your name.[e]

[dlg GENERIC_HELP_94]
[s]Choose a type of battle[n]to start, then begin[n]the fight![e]

[dlg GENERIC_HELP_95]
[s]Clip through walls and explore[n]out of bounds areas. Hold[n]Square to change axis.[e]

[dlg GENERIC_HELP_96]
[s]Select a BGM ID to[n]play back an audio track.[e]

[dlg GENERIC_HELP_97]
[s]Enter the ID of a field pack[n]to warp to that map.[e]

[dlg GENERIC_HELP_98]
[s]Enter the ID of an event pack[n]to start the event.[e]

[dlg GENERIC_HELP_99]
[s]Change the camera's position,[n]rotation, and field of view.[e]

[dlg GENERIC_HELP_100]
[s]Spawn NPC models and[n]preview their animations.[e]

[dlg GENERIC_HELP_101]
[s]Change various values[n]in the game's memory.[e]

[dlg GENERIC_HELP_102]
[s]Set a date and time and[n]travel directly to it.[e]

[dlg GENERIC_HELP_103]
[s]Test the dialogue cutins for[n]party members.[e]

[dlg GENERIC_HELP_104]
[s]Test the character placement[n]in the game's font.[e]

[dlg GENERIC_HELP_105]
[s]View your IM messages[n]or auto heal the party[n]just like the Square Button is[n]supposed to do.[e]

[dlg GENERIC_HELP_106]
[s]Show some info about the[n]development of this mod.[e]


[dlg PlayerMenuName]
Player Options[w][e]

[sel PlayerMenu]
[s]Personas[f 4 26 0 109][e]
[s]Social Stats[f 4 26 1 110][e]
[s]Items[f 4 26 2 111][e]
[s]Set Confidant Rank[f 4 26 3 112][e]
[s]Set Protag Name[f 4 26 4 113][e]
[s]Set Team Name[f 4 26 5 114][e]
[s]Animation Test[f 4 26 6 115][e]
[s]Set Scale[f 4 26 7 116][e]
[s]Attach Item Model[f 4 26 8 117][e]
[s]Max Money[f 4 26 9 118][e]

[dlg GENERIC_HELP_109]
[s]Add or remove your Personas, or[n]give you or your party[n]members new Skills.[e]

[dlg GENERIC_HELP_110]
[s]Add points to your Knowledge,[n]Charm, Proficiency, Guts[n]or Kindness.[e]

[dlg GENERIC_HELP_111]
[s]Give yourself a desired amount of[n]any consumables, weapons, armor,[n]costumes, or even key items.[e]

[dlg GENERIC_HELP_112]
[s]Select a Confidant and set your[n]current rank with their Arcana.[e]

[dlg GENERIC_HELP_113]
[s]Rename the protagonist at any[n]point in the game.[n][e]

[dlg GENERIC_HELP_114]
[s]Change the group name of the[n]Phantom Thieves at any[n]point in the game.[n][e]

[dlg GENERIC_HELP_115]
[s]Select one of the protagonist's[n]Field GAP files and view[n]its animations.[e]

[dlg GENERIC_HELP_116]
[s]Change the size of the[n]selected model.[e]

[dlg GENERIC_HELP_117]
[s]Enter an item's model ID[n]to attach it to the[n]protagonist's right hand.[e]

[dlg GENERIC_HELP_118]
[s]Adds 9,999,999 yen to your[n]wallet.[e]

[dlg ItemMenuName]
Select Item Type...[w][e]

[sel ItemMenu]
Consumables[f 4 26 0 121][e]
Accessories[f 4 26 1 122][e]
Key Items[f 4 26 2 123][e]
Ranged Weapons[f 4 26 3 124][e]
Melee Weapons[f 4 26 4 125][e]
Outfits[f 4 26 5 126][e]
Armor[f 4 26 6 127][e]
Materials[f 4 26 7 128][e]
Skill Cards[f 4 26 8 129][e]

[dlg GENERIC_HELP_121]
[s]Items that recover HP & SP,[n]relieve status ailments, or[n]provide buffs or debuffs.[e]

[dlg GENERIC_HELP_122]
[s]Items that you can equip to your[n]party members for stat[n]enhancements.[e]

[dlg GENERIC_HELP_123]
[s]Passive items that are acquired[n]throughout the story.[e]

[dlg GENERIC_HELP_124]
[s]Arms that can be equipped to[n]fire bullets during battle.[e]

[dlg GENERIC_HELP_125]
[s]Weapons used for basic physical[n]attacks during battle.[e]

[dlg GENERIC_HELP_126]
[s]Equippable appearance changes[n]for party members that modify[n]their model in the Metaverse.[e]

[dlg GENERIC_HELP_127]
[s]Equippable items that can boost[n]defense or provide other benefits.[e]

[dlg GENERIC_HELP_128]
[s]Items that can be sold to Iwai[n]or used to create tools.[e]

[dlg GENERIC_HELP_129]
[s]Items that can be used to assign[n]Skills to one of your Personas.[e]


[dlg CommuMenuName]
Select Confidant...[w][e]

[sel CommuMenu]
Igor[f 4 26 0 132][e]
Morgana[f 4 26 1 133][e]
Makoto Niijima[f 4 26 2 134][e]
Haru Okumura[f 4 26 3 135][e]
Yusuke Kitagawa[f 4 26 4 136][e]
Sojiro Sakura[f 4 26 5 137][e]
Ann Takamaki[f 4 26 6 138][e]
Ryuji Sakamoto[f 4 26 7 139][e]
Goro Akechi[f 4 26 8 140][e]
Futaba Sakura[f 4 26 9 141][e]
Chihaya Mifune[f 4 26 10 142][e]
Caroline and Justine[f 4 26 11 143][e]
Munehisa Iwai[f 4 26 12 144][e]
Tae Takemi[f 4 26 13 145][e]
Sayado Kawakami[f 4 26 14 146][e]
Ichiko Ohya[f 4 26 15 147][e]
Shinya Oda[f 4 26 16 148][e]
Hifumi Togo[f 4 26 17 149][e]
Yuuki Mishima[f 4 26 18 150][e]
Toranosuke Yoshida[f 4 26 19 151][e]
Sae Niijima[f 4 26 20 152][e]

[dlg GENERIC_HELP_132]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Fool[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_133]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Magician[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_134]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Priestess[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_135]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Empress[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_136]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Emperor[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_137]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Heirophant[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_138]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Lovers[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_139]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Chariot[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_140]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Justice[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_141]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Hermit[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_142]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Fortune[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_143]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Strength[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_144]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Hanged Man[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_145]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Death[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_146]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Temperance[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_147]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Devil[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_148]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Tower[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_149]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Star[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_150]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Moon[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_151]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Sun[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_152]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Judgement[clr 0][n]Arcana.[e]

[dlg UNUSED_HELP_59]
[s]Set the desired rank for[n]the Confidant of the [clr 9]World[clr 0][n]Arcana.[e]

[dlg StatsMenuName]
Select Stat Type...[w][e]

[sel StatsMenu]
Knowledge[f 4 26 0 156][e]
Charm[f 4 26 1 157][e]
Proficiency[f 4 26 2 158][e]
Guts[f 4 26 3 159][e]
Kindness[f 4 26 4 160][e]

[dlg GENERIC_HELP_156]
[s]Increase your [clr 26]Knowledge[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_157]
[s]Increase your [clr 26]Charm[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_158]
[s]Increase your [clr 26]Proficiency[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_159]
[s]Increase your [clr 26]Guts[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_160]
[s]Increase your [clr 26]Kindness[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg StatPrompt [Stats]]
Add how many points?[n](max. 2 digits, press Circle to end)[w][e]

[dlg ItemPrompt [Items]]
Enter the item ID you want.[n](max. 4 digits, press Circle to end)[w][e]

[dlg ItemPrompt2 [Items]]
Enter how many items you want.[n](max. 2 digits, press Circle to end)[w][e]

[dlg CmmDialog [Confidant Rank]]
Enter the Confidant's Arcana ID.[n](max. 2 digits, press Circle to end)[w][e]

[dlg CmmDialog2 [Confidant Rank]]
Enter the desired Confidant rank.[w][e]


[dlg AnimMenuName]
Player Animation[w][e]

[sel AnimMenu]
Field Animation Test[e]
Morgana Out of Bag[e]
Morgana In Bag[e]
Show Bag[e]
Hide Bag[e]
Umbrella On[e]
Umbrella Off[e]

[dlg GAPMenuName]
GAP Playback[w][e]

[sel GAPMenu]
Set GAP ID[f 4 26 0 170][e]
Set GAP Index[f 4 26 1 171][e]
Toggle Loop[f 4 26 2 172][e]
Set Speed[f 4 26 3 173][e]
Set Time[f 4 26 4 174][e]
Playback animation[f 4 26 5 175][e]

[dlg GENERIC_HELP_170]
[s]Input the filename of[n]a [clr 9]field GAP file for[clr 0][n]this character. (Starts with [clr 9]af[clr 0])[e]

[dlg GENERIC_HELP_171]
[s]Input the index of the[n]animation from the [clr 26]GAP[clr 0][n]that you want to view.[e]

[dlg GENERIC_HELP_172]
[s]Decide whether you want[n]the animation to repeat or not[n]when it's finished.[e]

[dlg GENERIC_HELP_173]
[s]Decide the playback speed[n]of the animation.[e]

[dlg GENERIC_HELP_174]
[s]Decide how many seconds you[n]would like to play the[n]animation for.[e]

[dlg GENERIC_HELP_175]
[s]Execute the animation playback[n][clr 9]after the above settings[clr 0][n]have been completed.[e]

[dlg ScalePrompt [Scale Model]]
Set the character's model scale.[n](press Circle to end)[n]Default is 10.[w][e]


[dlg CameraMenuName]
Camera Options[w][e]

[sel CameraMenu]
Reposition Camera[f 4 26 0 179][e]
Adjust FOV[f 4 26 1 180][e]
Adjust Zoom[f 4 26 2 181][e]
Rotate Camera[f 4 26 3 182][e]
Unlock Camera[f 4 26 4 183][e]
Lock Camera[f 4 26 5 184][e]
Disable Camera Shake[f 4 26 6 185][e]

[dlg GENERIC_HELP_179]
[s]Move the camera along the X, Y[n]or Z axis. Hold Square to change[n]the axis.[e]

[dlg GENERIC_HELP_180]
[s]Adjust the camera's[n]Field of View.[e]

[dlg GENERIC_HELP_181]
[s]Zoom the camera in[n]and out.[e]

[dlg GENERIC_HELP_182]
[s]Change the orientation of the[n]camera with the D-pad.[e]

[dlg GENERIC_HELP_183]
[s]Make the camera follow the player[n]again if previously locked.[e]

[dlg GENERIC_HELP_184]
[s]Makes the camera stationary,[n]which is required to modify it.[e]

[sel OneThruTen]
1[e]
2[e]
3[e]
4[e]
5[e]
6[e]
7[e]
8[e]
9[e]
10[e]

[dlg CalendarMenuName]
Calendar Options[w][e]

[sel CalendarMenu]
Set Next Day[f 4 26 0 188][e]
Call Calendar[f 4 26 1 189][e]
Set Weather[f 4 26 2 190][e]
Loop Current Day[f 4 26 3 191][e]

[dlg GENERIC_HELP_188]
[s]Choose the day and month[n]to warp to.[e]

[dlg GENERIC_HELP_189]
[s]End the current day and warp[n]to the next specified day.[e]

[dlg GENERIC_HELP_190]
[s]Change the current weather[n]condition value. Weather should[n]change after reloading map.[e]

[dlg GENERIC_HELP_191]
[s]Sets the current time[n]of day to be next after[n]ending the current day.[e]

[dlg CalendarPrompt[Calendar]]
Choose what month to start in.[n](press Circle to end)[w][e]

[dlg CalendarPrompt2 [Calendar]]
Choose what day to start on.[n](max. 2 digits, press Circle to end)[w][e]

[dlg EventDlg [Event Select]]
Choose the first 3 digits of
[n]the event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg EventDlg2 [Event Select]]
Choose the last 3 digits of
[n]the event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg KfEventDlg [KeyFree Event Select]]
Choose the first 3 digits of
[n]the KeyFree event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg KfEventDlg2 [KeyFree Event Select]]
Choose the last 3 digits of
[n]the KeyFree event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg FieldDlg [Field Select]]
Choose the first 3 digits of
[n]the field to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg FieldDlg2 [Field Select]]
Choose the last 3 digits of
[n]the field to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg SpawnMenuName]
NPC Options[w][e]

[sel SpawnMenu]
Spawn Model[f 4 26 0 202][e]
Animate Model[f 4 26 1 203][e]
Set Model Scale[f 4 26 2 204][e]
Attach Item Model[f 4 26 3 205][e]
Spawn Object Model[f 4 26 4 206][e]

[dlg GENERIC_HELP_202]
[s]Input a [clr 9]GMD filename[clr 0][n]to spawn a character model from.[e]

[dlg GENERIC_HELP_203]
[s]Apply field animations[n]to the last NPC you spawned.[e]

[dlg GENERIC_HELP_204]
[s]Set the scale of the[n]NPC model.[e]

[dlg GENERIC_HELP_205]
[s]Input a [clr 9]GMD filename[clr 0][n]to attach to the NPC.[e]

[dlg GENERIC_HELP_206]
[s]Input a [clr 9]GMD filename[clr 0][n]of an object to spawn.[e]

[dlg PersonaMenuName]
Persona Options[w][e]

[sel PersonaMenu]
Add Persona[f 4 26 0 209][e]
Delete Personas[f 4 26 1 210][e]
Add Skill[f 4 26 2 211][e]
Unlock Full Compendium[f 4 26 3 212][e]
Evolve Persona[f 4 26 4 213][e]

[dlg GENERIC_HELP_209]
[s]Input a Persona's name or ID[n]to add it to your stock.[e]

[dlg GENERIC_HELP_210]
[s]Permanently remove all Personas[n]from your current stock.[e]

[dlg GENERIC_HELP_211]
[s]Choose a party member and the[n]name or ID of a Skill to add[n]to their current Persona.[e]

[dlg GENERIC_HELP_212]
[s]Register every Persona in[n]the game by filling your[n]stock with them all.[e]

[dlg GENERIC_HELP_213]
[s]Evolve a party member's Persona[n]into its Ultimate form.[e]


[dlg UnitMenuName]
Select Party Member[w][e]

[sel UnitSelect]
Joker[e]
Ryuji[e]
Morgana[e]
Ann[e]
Yusuke[e]
Makoto[e]
Haru[e]
Futaba[e]
Akechi[e]

[sel UnitSelect2]
Ryuji[e]
Morgana[e]
Ann[e]
Yusuke[e]
Makoto[e]
Haru[e]
Futaba[e]
Akechi[e]

[dlg PersonaDelPrompt [Delete Personas]]
This will permanently remove all 
[n]Personas in your stock. Are you sure?[w][e]

[dlg UnitPrompt [Add Skill]]
Choose a character to add a skill to
[n]their currently equipped Persona.[w][e]

[dlg SkillPrompt [Add Skill]]
Enter the ID of the skill to add.
[n](max. 3 digits, press Circle to end)[w][e]

[dlg PersonaAddPrompt [Add Persona]]
Input the ID of the Persona to add.
[n](max. 3 digits, press Circle to end)[w][e]

[dlg NPCPrompt [Model Select]]
Set the first (4 digits) of the NPC
[n]filename to load. (Press Circle to end)[w][e]

[dlg NPCPrompt2 [Model Select]]
Set the next (3 digits) of the NPC
[n]model filename to load. (Press Circle to end)[w][e]

[dlg NPCPrompt3 [Model Select]]
Set the last (2 digits) of the NPC
[n]model filename to load. (Press Circle to end)[w][e]

[dlg GapPrompt [Animation Test]]
Select the GAP ID.
[n](max. 3 digits, press Circle to end)[w][e]

[dlg GapPrompt2 [Animation Test]]
Select which animation to play.
[n](max. 2 digits, press Circle to end)[w][e]

[dlg GapPrompt3 [Animation Test]]
Select whether to loop or not.[w][e]

[dlg GapPrompt4 [Animation Test]]
Select the third parameter.
[n](max. 2 digits, press Circle to end)[w][e]

[dlg GapPrompt5 [Animation Test]]
Select the animation speed. Default is 10.
[n](max. 2 digits, press Circle to end)[w][e]

[dlg GapPrompt6 [Animation Test]]
Select the number of seconds to play.[w][e]

[dlg CameraPrompt [Camera Mode]]
Use the D-Pad to manipulate the camera.
[n]Press Triangle to quit.
[n](Camera must be locked first!)[w][e]

[dlg SelectBgmDialog [Ultimate DJ TGE]]
Select a bgm to play.[w][e]

[dlg FlagMenuName]
Flag Options[w][e]

[sel FlagMenu]
HUD Display[f 4 26 0 234][e]
Add Party Members[f 4 26 1 235][e]
Remove Party Members[f 4 26 2 236][e]
Enable Party Editing[f 4 26 3 237][e]
Unlock All Persona Slots[f 4 26 4 238][e]
Add Overworld Follower[f 4 26 5 239][e]
Navigator[f 4 26 6 240][e]
Change Romance Route[f 4 26 7 241][e]
Room Editor[f 4 26 8 242][e]
Manual Input[f 4 26 9 243][e]
Print Enabled Flags[f 4 26 10 244][e]
Mass Flag Editor[f 4 26 11 245][e]

[dlg GENERIC_HELP_234]
[s]Show or hide the user interface[n]elements, such as the date, time,[n]and mission list.[e]

[dlg GENERIC_HELP_235]
[s]Make a Persona user available to[n]add to your party.[e]

[dlg GENERIC_HELP_236]
[s]Revoke a Persona user's[n]availability to be added[n]to your party.[e]

[dlg GENERIC_HELP_237]
[s]Allow choosing your own[n]party members from the Stats[n]menu in the pause menu.[e]

[dlg GENERIC_HELP_238]
[s]Unlocks all 12 Persona slots.[e]

[dlg GENERIC_HELP_239]
[s]Enable or disable party[n]members following you[n]in the overworld.[e]

[dlg GENERIC_HELP_240]
[s]Change which character[n]currently serves as the Navigator.[e]

[dlg GENERIC_HELP_241]
[s]Start or end a relationship with[n]a female Confidant.[e]

[dlg GENERIC_HELP_242]
[s]Modify the state of the[n]protagonist's bedroom in[n]the Leblanc attic.[e]

[dlg GENERIC_HELP_243]
[s]Enter an 4-digit decimal value[n]of a bit to either[n]enable or disable it.[e]

[dlg GENERIC_HELP_244]
[s]Print all currently enabled[n]bit flag values to the[n]TTY log.[e]

[dlg GENERIC_HELP_245]
[s]Manipulate a selected[n]range of bit flags to[n]toggle or print.[e]

[dlg FieldMenuName]
Field Select[e]

[sel FieldMenu]
Enter Field ID[f 4 26 0 248][e]
Load Field[f 4 26 1 249][e]
Reload Current Field[f 4 26 2 250][e]

[dlg GENERIC_HELP_248]
[s]Input the 6 digits of a[n][clr 9]field pack's[clr 0] filename[n](found in ps3.cpk/field)[e]

[dlg GENERIC_HELP_249]
[s]Attempt to load the selected[n]field. [clr 9]WARNING: Some fields may[n]softlock the game.[clr 0][e]

[dlg GENERIC_HELP_250]
[s]Reload the field that[n]you're currently on.[e]

[dlg EventMenuName]
Event Select[e]

[sel EventMenu]
Enter Event ID[f 4 26 0 253][e]
Load Event[f 4 26 1 254][e]
Enter KeyFree Event ID[f 4 26 2 255][e]
Load KeyFree Event[f 4 26 3 256][e]

[dlg GENERIC_HELP_253]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](found in data.cpk/event)[e]

[dlg GENERIC_HELP_254]
[s]Attempt to load the selected[n]event. [clr 9]WARNING: Some events may[n]softlock the game.[clr 0][e]

[dlg GENERIC_HELP_255]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](found in ps3.cpk/field).[clr 0][e]

[dlg GENERIC_HELP_256]
[s]Attempt to load the selected[n]KeyFree event. [clr 9]WARNING: Some events may[n]softlock the game.[clr 0][e]

[dlg NaviMenuName]
Select Navigator[w][e]

[sel NaviMenu]
Morgana[e]
Futaba[e]
None[e]

[sel DateDisplayDlg]
Enable[e]
Disable[e]

[dlg LoveMenuName]
Select Relationship[w][e]

[sel LoveMenu]
Makoto[e]
Haru[e]
Ann[e]
Futaba[e]
Chihaya[e]
Takemi[e]
Kawakami[e]
Ohya[e]
Hifumi[e]

[dlg AboutDlg[About this menu]]
Created by [clr 1]TGE[clr 0], [clr 6]ShrineFox[clr 0] and [clr 15]CaptainSwag101[clr 0]
[n]using TGE's [clr 9]AtlusScriptCompiler[clr 0] tool. Visit
[n]https://amicitia.github.io to learn more![w][e]

[sel RoomEdit]
Furniture[e]
Collectibles[e]
Cleanliness[e]

[sel FurnEdit]
Plant[e]
Sayuri[e]
DVD Player[e]
Game Console[e]
Old TV Set[e]
Radio[e]
Cat Bed[e]
UFO Game Prizes...[e]

[sel CollEdit]
Swan Boat[e]
Ramen[e]
Pennant[e]
Statue[e]
Sky Tree[e]
Big Hera[e]
Shumai[e]
Fusen[e]
I Love[e]
Idol[e]
More...[e]

[sel CollEdit2]
Seiza[e]
Syogi[e]
Hero[e]
Hamaya[e]
Jyainyan[e]
Sushi[e]
Choco[e]
Kumade[e]
Prev...[e]

[sel CleanEdit]
Bookshelf[e]
Workbench[e]
Visitor Table[e]
Training Chair[e]
Winter Heater[e]
Laptop[e]

[dlg MonthMenuName]
Select a Month[e]

[sel MonthMenu]
January[e]
February[e]
March[e]
April[e]
May[e]
June[e]
July[e]
August[e]
September[e]
October[e]
November[e]
December[e]

[dlg CalendarError]
Invalid day selected.[n]
Please try again.[w][e]

[dlg CalendarBackwardsError]
You can only go back one day at a time.[w][e]

[dlg SelectBossName]
Boss Event Select[w][e]

[sel Palace1]
Battle Scenario 1[e]
Battle with Morgana[e]
Battle Scenario 2[e]
Battle Scenario 3[e]
Sub Battle 1[e]
Sub Battle 2[e]
Gun Tutorial[e]
Hold Up Tutorial[e]
All Out Attack Tutorial[e]
Persona Recruit Tutorial[e]
Mini Boss 1[e]
Mini Boss 2[e]
Shadow Kamoshida[e]

[sel Palace2]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Battle Scenario[e]
Shadow Madarame[e]

[sel Palace3]
Battle Scenario[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Mini Boss 5[e]
Shadow Kaneshiro[e]

[sel Palace4]
Bandit[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Shadow Wakaba[e]

[sel Palace5]
Cognitive Sugimura[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Shadow Okumura[e]

[sel Palace6]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3 (05_B)[e]
Mini Boss 4 (05_BOSS)[e]
Akechi's First Battle[e]
Mini Boss (Dark Zone)[e]
Mini Boss (Camera Room)[e]
Mini Boss (Dice)[e]
Slot (ENYRY) Battle[e]
Escape Battle[e]
Shadow Sae[e]

[sel Palace7]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
First Target[e]
Second Target[e]
Third Target[e]
Fourth Target[e]
Fifth Target[e]
Akechi[e]
Shadow Shido[e]

[sel Palace8]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
The Holy Grail[e]
The Twins[e]
Uriel[e]
Raphael[e]
Gabriel[e]
Michael[e]
Yaldabaoth[e]

[sel Misc1]
Prologue Battle[e]
QUEST_BATTLE[e]
Yusuke Co-op[e]
int_CLEAR[e]
ALERT_CLEAR_EX[e]
PALACE_CLEAR_SYS[e]
PALACE_CALL_CALENDAR[e]
Closest encounter to position[e]
D_ENCOUNT_START[e]
dungeon_return_calendar[e]
dungeon_return[e]
Next[e]

[sel Misc2]
dungeon_exit_time_set[e]
dungeon_start_format[e]
DUNGEON_START_SAVE[e]
result_counter_clear[e]
MVP_CHOICE (CRASH!)[e]
D_ENCOUNT_NO_GET[e]
Dummy[e]
Dummy[e]
Previous[e]

[dlg HudTest1]
HUD has been enabled.[w][e]

[dlg HudTest2]
HUD has been disabled.[w][e]

[dlg PersonaAdded]
The chosen Persona has been[n]added to your stock.[w][e]

[dlg PersonaDeleted]
All Personas have been deleted.[w][e]

[dlg WeatherChanged]
Weather has been changed.[w][e]

[dlg LoadCheckError]
Set the required parameters[n]before attempting to load![w][e]

[dlg WeatherMenuName]
Weather Select[w][e]

[sel WeatherMenu]
Sunny[e]
Rainy[e]
Cloudy[e]
Snow[e]
Rainy Season[e]
Typhoon Warning[e]
Sunny Pollen Warning[e]
Cloudy Pollen Warning[e]
Torrential Rain[e]
Sunny Heatwave/Hot Night[e]
Sunny Flu Season[e]
Cloudy Flu Season[e]

[dlg BattleTypeName]
Battle Type Select[w][e]

[sel BattleTypeMenu]
Regular Encounter[e]
Boss Encounter[e]
Event Battle[e]

[dlg EventBattleName]
Battle Type Select[w][e]

[sel PalaceMenu]
Castle[e]
Art Museum[e]
First World Bank[e]
Pyramid[e]
Space Station[e]
Casino[e]
Cruise Ship[e]
Mementos Depths[e]
Misc[e]

[dlg PalaceName]
Palace Select[e]

[sel EventBattleSelect]
Akechi[e]
Akechi Phase 2[e]
Holy Grail[e]
Yaldabaoth[e]
Velvet Twins[e]
MISC[e]

[dlg EncounterPrompt]
Set the number of the encounter[n]you want to fight (3 digits).[w][e]

[sel FlagMassEditor]
Disable all flags[e]
Enable all flags[e]
Swap enabled/disabled flags[e]
Toggle range of flags[e]
Clear Inherit Data[e]

[dlg PersonaAddSkillMenuName]
Persona Options[w][e]

[sel PersonaAddSkillMenu]
Add Skill[e]
Add Skill (Manual Input)[e]

[dlg PersonaAddMenuName]
Persona Options[w][e]

[sel PersonaAddMenu]
Add Persona[e]
Add Persona (Manual Input)[e]

[dlg BagShowHide]
The bag has been toggled.[n]To see the change, go to a new field[n]or reload the current one.[w][e]

[dlg GENERIC_HELP_304]
Removes the swaying effect[n]of the camera that's[n]used in dungeons.[w][e]

[dlg GENERIC_HELP_305]
Select an item's model ID to[n]spawn it and connect it to[n]the character's model.[w][e]

[dlg GENERIC_HELP_306]
Select a range of flags[n]to either enable or disable.[w][e]

[dlg ItemSpawnPrompt]
Enter the first half of the model's[n]ID from data.cpk/model/item.[n](Max 4 digits, press Circle to end).[w][e]

[dlg ItemSpawnPrompt2]
Enter the last half of the model's[n]ID from data.cpk/model/item.[n](Max 3 digits, press Circle to end).[w][e]

[dlg ObjectSpawnPrompt]
Enter the first half of the[n]model's ID from data.cpk/model/field_tex/object.[n](Max 3 digits, press Circle to end).[w][e]

[dlg ObjectSpawnPrompt2]
Enter the last half of the[n]model's ID from data.cpk/model/field_tex/object.[n](Max 3 digits, press Circle to end).[w][e]

[dlg FlagRangePrompt]
Enter the start of the[n]range to narrow down.[n](Max 4 digits, press Circle to end).[w][e]

[dlg FlagRangePrompt2]
Enter the end of the[n]range to narrow down.[n](Max 4 digits, press Circle to end).[w][e]

[dlg GENERIC_HELP_313]
Unlocks all Personas in the[n]Compendium. [clr 9]This will delete all[n]Personas in your current stock![clr 0][w][e]

[dlg FontMenuName]
Font Test Options[w][e]

[sel FontTestMenu]
[s]Sample text[f 4 26 0 316][e]
[s]Uppercase[f 4 26 1 317][e]
[s]Lowercase[f 4 26 2 318][e]
[s]Symbols[f 4 26 3 319][e]
[s]All-in-One[f 4 26 4 320][e]

[dlg GENERIC_HELP_316]
[s]Print a sample sentence[n]for font testing.[e]

[dlg GENERIC_HELP_317]
[s]Print a text message with[n]uppercase letters.[e]

[dlg GENERIC_HELP_318]
[s]Print a text message with[n]lowercase letters.[e]

[dlg GENERIC_HELP_319]
[s]Print a text message with[n]numbers and special[n]characters.[e]

[dlg GENERIC_HELP_320]
[s]Print a text message with[n]all the characters.[e]

[dlg FontTest0[The Font Guy]]
[s]The quick brown fox jumps over[n]the lazy dog. 1234567890[n][w][e]

[dlg FontTest1[The Font Guy]]
[s]ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]A B C D E F G H I J K L M N O P Q R S T U V W X Y Z[w][e]

[dlg FontTest2[The Font Guy]]
[s]abcdefghijklmnopqrstuvwxyz[n]a b c d e f g h i j k l m n o p q r s t u v w x y z[w][e]

[dlg FontTest3[The Font Guy]]
[s]1234567890-_.:,;|!"#$%&/()=?+*{}^\<>`~'@[n][w][e]

[dlg FontTest4[The Font Guy]]
[s]ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]abcdefghijklmnopqrstuvwxyz[n]1234567890-_.:,;|!"#$%&/()=?+*{}^\<>`~'@[w][e]

[dlg PartyMemberCutinMenuName]
Party Member Cutin Test[w][e]

[sel PartyCharacterSelect]
[s]Ryuji[f 4 26 0 328][e]
[s]Morgana[f 4 26 1 329][e]
[s]Ann[f 4 26 2 330][e]
[s]Yusuke[f 4 26 3 331][e]
[s]Makoto[f 4 26 4 332][e]
[s]Haru[f 4 26 5 333][e]
[s]Futaba[f 4 26 6 334][e]
[s]Akechi[f 4 26 7 335][e]
[s]Goro[f 4 26 8 336][e]

[dlg GENERIC_HELP_328]
[s]Test the dialogue cutins[n]for Ryuji Sakamoto.[e]

[dlg GENERIC_HELP_329]
[s]Test the dialogue cutins[n]for Morgana.[e]

[dlg GENERIC_HELP_330]
[s]Test the dialogue cutins[n]for Ann Takamaki.[e]

[dlg GENERIC_HELP_331]
[s]Test the dialogue cutins[n]for Yusuke Kitagawa.[e]

[dlg GENERIC_HELP_332]
[s]Test the dialogue cutins[n]for Makoto Nijima.[e]

[dlg GENERIC_HELP_333]
[s]Test the dialogue cutins[n]for Haru Okumura.[e]

[dlg GENERIC_HELP_334]
[s]Test the dialogue cutins[n]for Futaba Sakura.[e]

[dlg GENERIC_HELP_335]
[s]Test the dialogue cutins[n]for Goro Akechi.[e]

[dlg GENERIC_HELP_336]
[s]Test the dialogue cutins[n]for Villain Akechi.[e]

[dlg CutinOrientationMenuName]
Cutin Orientation[w][e]

[sel CutinOrientation]
[s]Right[e]
[s]Left[e]

[dlg RyujiExpressionRight[Ryuji]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 0 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 1 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 2 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 3 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 4 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 5 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 6 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 7 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 10 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 11 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 12 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 13 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 14 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 15 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 16 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 17 301 1]Cutin Test[n][w][e]

[dlg RyujiExpressionLeft[Ryuji]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 0 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 1 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 2 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 3 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 4 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 5 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 6 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 7 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 10 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 11 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 12 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 13 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 14 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 15 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 16 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 2 17 300 1]Cutin Test[n][w][e]

[dlg MorganaExpressionRight[Morgana]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 0 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 1 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 2 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 3 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 4 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 5 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 6 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 7 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 10 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 11 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 12 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 13 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 14 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 15 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 16 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 17 301 1]Cutin Test[n][w][e]

[dlg MorganaExpressionLeft[Morgana]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 0 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 1 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 2 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 3 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 4 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 5 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 6 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 7 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 10 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 11 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 12 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 13 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 14 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 15 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 16 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 3 17 300 1]Cutin Test[n][w][e]

[dlg AnnExpressionRight[Ann]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 0 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 1 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 2 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 3 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 4 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 5 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 6 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 7 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 10 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 11 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 12 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 13 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 14 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 15 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 16 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 17 301 1]Cutin Test[n][w][e]

[dlg AnnExpressionLeft[Ann]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 0 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 1 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 2 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 3 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 4 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 5 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 6 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 7 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 10 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 11 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 12 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 13 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 14 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 15 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 16 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 4 17 300 1]Cutin Test[n][w][e]

[dlg YusukeExpressionRight[Yusuke]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 0 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 1 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 2 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 3 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 4 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 5 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 6 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 7 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 10 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 11 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 12 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 13 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 14 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 15 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 16 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 17 301 1]Cutin Test[n][w][e]

[dlg YusukeExpressionLeft[Yusuke]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 0 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 1 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 2 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 3 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 4 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 5 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 6 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 7 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 10 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 11 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 12 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 13 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 14 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 15 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 16 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 5 17 300 1]Cutin Test[n][w][e]

[dlg MakotoExpressionRight[Makoto]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 0 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 1 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 2 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 3 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 4 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 5 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 6 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 7 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 10 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 11 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 12 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 13 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 14 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 15 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 16 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 17 301 1]Cutin Test[n][w][e]

[dlg MakotoExpressionLeft[Makoto]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 0 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 1 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 2 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 3 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 4 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 5 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 6 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 7 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 10 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 11 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 12 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 13 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 14 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 15 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 16 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 6 17 300 1]Cutin Test[n][w][e]

[dlg HaruExpressionRight[Haru]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 0 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 1 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 2 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 3 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 4 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 5 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 6 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 7 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 10 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 11 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 12 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 13 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 14 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 15 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 16 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 17 301 1]Cutin Test[n][w][e]

[dlg HaruExpressionLeft[Haru]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 0 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 1 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 2 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 3 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 4 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 5 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 6 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 7 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 10 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 11 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 12 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 13 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 14 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 15 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 16 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 7 17 300 1]Cutin Test[n][w][e]

[dlg FutabaExpressionRight[Futaba]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 0 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 1 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 2 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 3 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 4 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 5 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 6 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 7 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 10 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 11 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 12 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 13 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 14 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 15 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 16 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 17 301 1]Cutin Test[n][w][e]

[dlg FutabaExpressionLeft[Futaba]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 0 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 1 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 2 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 3 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 4 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 5 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 6 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 7 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 10 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 11 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 12 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 13 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 14 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 15 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 16 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 8 17 300 1]Cutin Test[n][w][e]

[dlg AkechiExpressionRight[Akechi]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 0 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 1 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 2 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 3 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 4 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 5 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 6 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 7 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 10 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 11 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 12 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 13 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 14 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 15 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 16 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 17 301 1]Cutin Test[n][w][e]

[dlg AkechiExpressionLeft[Akechi]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 0 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 1 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 2 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 3 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 4 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 5 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 6 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 7 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 10 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 11 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 12 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 13 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 14 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 15 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 16 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 9 17 300 1]Cutin Test[n][w][e]

[dlg GoroExpressionRight[Goro]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 10 3 301 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 10 10 301 1]Cutin Test[n][w][e]

[dlg GoroExpressionLeft[Goro]]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 10 3 300 1]Cutin Test[n][w][e]
[s][f 4 17 1 -1 -1 -1 -1 -1 -1 -1 10 10 300 1]Cutin Test[n][w][e]