[dlg ModMenuName]
Amicitia Mod Menu[w][e]

[sel ModMenu]
[s]Exit[f 4 26 0 2][e]
[s]Player[f 4 26 1 3][e]
[s]Boss Select[f 4 26 2 4][e]
[s]Teleport[f 4 26 3 5][e]
[s]Sound Test[f 4 26 4 6][e]
[s]Field Select[f 4 26 5 7][e]
[s]Event Select[f 4 26 6 8][e]
[s]Camera[f 4 26 7 9][e]
[s]NPCs[f 4 26 8 10][e]
[s]Flags[f 4 26 9 11][e]
[s]Calendar[f 4 26 10 12][e]
[s]Check Phone/Auto Recover[f 4 26 11 13][e]
[s]About[f 4 26 12 14][e]

[dlg GENERIC_HELP_2]
[s]Back out of this menu and[n]resume normal gameplay.[e]

[dlg GENERIC_HELP_3]
[s]Edit your Personas, items, stats,[n]money, or even your name.[e]

[dlg GENERIC_HELP_4]
[s]Choose a scene to start[n]a boss encounter.[e]

[dlg GENERIC_HELP_5]
[s]Clip through walls and explore[n]out of bounds areas. Hold[n]Square to change axis.[e]

[dlg GENERIC_HELP_6]
[s]Select a BGM ID to[n]play back an audio track.[e]

[dlg GENERIC_HELP_7]
[s]Enter the ID of a field pack[n]to warp to that map.[e]

[dlg GENERIC_HELP_8]
[s]Enter the ID of an event pack[n]to start the event.[e]

[dlg GENERIC_HELP_9]
[s]Change the camera's position,[n]rotation, and field of view.[e]

[dlg GENERIC_HELP_10]
[s]Spawn NPC models and[n]preview their animations.[e]

[dlg GENERIC_HELP_11]
[s]Change various values[n]in the game's memory.[e]

[dlg GENERIC_HELP_12]
[s]Set a date and time and[n]travel directly to it.[e]

[dlg GENERIC_HELP_13]
[s]View your IM messages[n]or auto heal the party[n]just like the Square Button is[n]supposed to do.[e]

[dlg GENERIC_HELP_14]
[s]Show some info about the[n]development of this mod.[e]


[dlg PlayerMenuName]
Player Options[w][e]

[sel PlayerMenu]
[s]Back[f 4 26 0 17][e]
[s]Personas[f 4 26 1 18][e]
[s]Stats[f 4 26 2 19][e]
[s]Items[f 4 26 3 20][e]
[s]Set Confidant Rank[f 4 26 4 21][e]
[s]Set Protag Name[f 4 26 5 22][e]
[s]Set Team Name[f 4 26 6 23][e]
[s]Animation Test[f 4 26 7 24][e]
[s]Set Scale[f 4 26 8 25][e]
[s]Max Money[f 4 26 9 26][e]

[dlg GENERIC_HELP_17]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]main selection page.[e]

[dlg GENERIC_HELP_18]
[s]Add or remove your personas, or[n]give you or your party[n]members new Skills.[e]

[dlg GENERIC_HELP_19]
[s]Add points to your Knowledge,[n]Charm, Proficiency, Guts[n]or Kindness.[e]

[dlg GENERIC_HELP_20]
[s]Give yourself a desired amount of[n]any consumables, weapons, armor,[n]costumes, or even key items.[e]

[dlg GENERIC_HELP_21]
[s]Select a Confidant and change your[n]current rank with their Arcana.[e]

[dlg GENERIC_HELP_22]
[s]Rename the protagonist at any[n]point in the game.[e]

[dlg GENERIC_HELP_23]
[s]Change the group name of the[n]Phantom Thieves at any[n]point in the game.[e]

[dlg GENERIC_HELP_24]
[s]Select one of the protagonist's[n]Field GAP files and view[n]its animations.[e]

[dlg GENERIC_HELP_25]
[s]Change the size of the[n]protagonist's model.[e]

[dlg GENERIC_HELP_26]
[s]Adds 999999 yen to your wallet.[e]


[dlg ItemMenuName]
Select Item Type...[w][e]

[sel ItemMenu]
Back[f 4 26 0 29][e]
Consumables[f 4 26 1 30][e]
Accessories[f 4 26 2 31][e]
Key Items[f 4 26 3 32][e]
Ranged Weapons[f 4 26 4 33][e]
Melee Weapons[f 4 26 5 34][e]
Outfits[f 4 26 6 35][e]
Armor[f 4 26 7 36][e]
Materials[f 4 26 8 37][e]
Skill Cards[f 4 26 9 38][e]

[dlg GENERIC_HELP_38]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]Player Options page.[e]

[dlg GENERIC_HELP_29]
[s]Items that recover HP & SP,[n]relieve status ailments, or[n]provide buffs or debuffs.[e]

[dlg GENERIC_HELP_30]
[s]Items that you can equip to your[n]party members for stat[n]enhancements.[e]

[dlg GENERIC_HELP_31]
[s]Passive items that are acquired[n]throughout the story.[e]

[dlg GENERIC_HELP_32]
[s]Arms that can be equipped to[n]fire bullets during battle.[e]

[dlg GENERIC_HELP_33]
[s]Where Melee weapons would be[n]if I knew the offset for them.[n]Sorry for the inconvenience![e]

[dlg GENERIC_HELP_34]
[s]Equippable appearance changes[n]for party members that modify[n]their model in the Metaverse.[e]

[dlg GENERIC_HELP_35]
[s]Equippable items that can boost[n]defense or provide other benefits.[e]

[dlg GENERIC_HELP_36]
[s]Items that can be sold to Iwai[n]or used to create tools.[e]

[dlg GENERIC_HELP_37]
[s]Items that can be used to assign[n]Skills to one of your Personas.[e]


[dlg CommuMenuName]
Select Confidant...[w][e]

[sel CommuMenu]
Back[f 4 26 0 41][e]
Igor[f 4 26 1 42][e]
Morgana[f 4 26 2 43][e]
Makoto Niijima[f 4 26 3 44][e]
Haru Okumura[f 4 26 4 45][e]
Yusuke Kitagawa[f 4 26 5 46][e]
Sojiro Sakura[f 4 26 6 47][e]
Ann Takamaki[f 4 26 7 48][e]
Ryuji Sakamoto[f 4 26 8 49][e]
Goro Akechi[f 4 26 9 50][e]
Futaba Sakura[f 4 26 10 51][e]
Chihaya Mifune[f 4 26 11 52][e]
Caroline and Justine[f 4 26 12 53][e]
Munehisa Iwai[f 4 26 13 54][e]
Tae Takemi[f 4 26 14 55][e]
Sayado Kawakami[f 4 26 15 56][e]
Ichiko Ohya[f 4 26 16 57][e]
Shinya Oda[f 4 26 17 58][e]
Hifumi Togo[f 4 26 18 59][e]
Yuuki Mishima[f 4 26 19 60][e]
Toranosuke Yoshida[f 4 26 20 61][e]
Sae Niijima[f 4 26 21 62][e]

[dlg GENERIC_HELP_63]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]Player Options page.[e]

[dlg GENERIC_HELP_41]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Fool[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_42]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Magician[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_43]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Priestess[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_44]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Empress[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_45]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Emperor[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_46]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Heirophant[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_47]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Lovers[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_48]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Chariot[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_49]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Justice[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_50]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Hermit[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_51]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Fortune[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_52]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Strength[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_53]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Hanged Man[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_54]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Death[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_55]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Temperance[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_56]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Devil[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_57]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Tower[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_58]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Star[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_59]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Moon[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_60]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Sun[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_61]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Judgement[clr 0][n]Arcana.[e]

[dlg UNUSED_HELP_96]
[s]Set the desired rank for[n]the Confidant of the [clr 9]World[clr 0][n]Arcana.[e]

[dlg StatsMenuName]
Select Stat Type...[w][e]

[sel StatsMenu]
Back[f 4 26 0 66][e]
Knowledge[f 4 26 1 67][e]
Charm[f 4 26 2 68][e]
Proficiency[f 4 26 3 69][e]
Guts[f 4 26 4 70][e]
Kindness[f 4 26 5 71][e]

[dlg GENERIC_HELP_71]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]Player Options page.[e]

[dlg GENERIC_HELP_66]
[s]Increase your [clr 26]Knowledge[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_67]
[s]Increase your [clr 26]Charm[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_68]
[s]Increase your [clr 26]Proficiency[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_69]
[s]Increase your [clr 26]Guts[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_70]
[s]Increase your [clr 26]Kindness[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg StatPrompt [Stats]]
Add how many points? (2 digits)[w][e]

[dlg ItemPrompt [Items]]
Enter the item ID you want. (4 digits)[w][e]

[dlg ItemPrompt2 [Items]]
Enter how many items you want. (2 digits)[w][e]

[dlg CmmDialog [Confidant Rank]]
Enter the Confidant's Arcana ID. (2 digits)[w][e]

[dlg CmmDialog2 [Confidant Rank]]
Enter the desired Confidant rank. (2 digits)[w][e]


[dlg AnimMenuName]
Player Animation...[w][e]

[sel AnimMenu]
Back[e]
Field Animation Test[e]
Morgana Out of Bag[e]
Morgana In Bag[e]


[dlg GAPMenuName]
GAP Playback[w][e]

[sel GAPMenu]
Back[f 4 26 0 81][e]
Set GAP ID[f 4 26 1 82][e]
Set GAP Index[f 4 26 2 83][e]
Toggle Loop[f 4 26 3 84][e]
Set Speed[f 4 26 4 85][e]
Set Time[f 4 26 5 86][e]
Playback animation[f 4 26 6 87][e]

[dlg GENERIC_HELP_87]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]previous page.[e]

[dlg GENERIC_HELP_81]
[s]Input the filename of[n]a [clr 9]field GAP file for[clr 0][n]this character. (Starts with [clr 9]af[clr 0])[e]

[dlg GENERIC_HELP_82]
[s]Input the index of the[n]animation from the [clr 26]GAP[clr 0][n]that you want to view.[e]

[dlg GENERIC_HELP_83]
[s]Decide whether you want[n]the animation to repeat or not[n]when it's finished.[e]

[dlg GENERIC_HELP_84]
[s]Decide the playback speed[n]of the animation.[e]

[dlg GENERIC_HELP_85]
[s]Decide how many seconds you[n]would like to play the[n]animation for.[e]

[dlg GENERIC_HELP_86]
[s]Execute the animation playback[n][clr 9]after the above settings[clr 0][n]have been completed.[e]

[dlg ScalePrompt [Scale Model]]
Set Joker's model scale (2 digits).
[n]Default is 10.[w][e]


[dlg CameraMenuName]
Camera Options[w][e]

[sel CameraMenu]
Back[f 4 26 0 91][e]
Reposition Camera[f 4 26 1 92][e]
Adjust FOV[f 4 26 2 93][e]
Rotate Camera[f 4 26 3 94][e]
Unlock Camera[f 4 26 4 95][e]
Lock Camera[f 4 26 5 96][e]

[dlg GENERIC_HELP_96]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]main selection page.[e]

[dlg GENERIC_HELP_91]
[s]Move the camera along the X, Y[n]or Z axis. Hold Square to change[n]the axis.[e]

[dlg GENERIC_HELP_92]
[s]Zoom the camera in and out by[n]changing the Field of View.[e]

[dlg GENERIC_HELP_93]
[s]Change the orientation of the[n]camera with the D-pad.[e]

[dlg GENERIC_HELP_94]
[s]Make the camera follow the player[n]again if previously locked.[e]

[dlg GENERIC_HELP_95]
[s]Makes the camera stationary,[n]which is required to modify it.[e]

[sel OneThruTen]
0[e]
1[e]
2[e]
3[e]
4[e]
5[e]
6[e]
7[e]
8[e]
9[e]
10[e]


[dlg CalendarMenuName]
Calendar Options[w][e]

[sel CalendarMenu]
Back[f 4 26 0 100][e]
Set Next Day[f 4 26 1 101][e]
Call Calendar[f 4 26 2 102][e]
Set Weather[f 4 26 3 103][e]

[dlg GENERIC_HELP_102]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]main selection page.[e]

[dlg GENERIC_HELP_100]
[s]Choose the day and month[n]to warp to.[e]

[dlg GENERIC_HELP_101]
[s]End the current day and warp[n]to the next specified day.[e]

[dlg GENERIC_HELP_103]
[s]Change the current weather[n]condition value. Weather should[n]change after reloading map.[e]

[dlg CalendarPrompt[Calendar]]
Choose what month to start in (2 digits).[w][e]

[dlg CalendarPrompt2[Calendar]]
Choose what day to start on (2 digits).[w][e]

[dlg EventDlg[Events]]
Choose the first 3 digits of
[n]the event to load (3 digits).[w][e]

[dlg EventDlg2[Events]]
Choose the last 3 digits of
[n]the event to load (3 digits).[w][e]

[dlg FieldDlg[Fields]]
Choose the first 3 digits of
[n]the field to load (3 digits).[w][e]

[dlg FieldDlg2[Fields]]
Choose the last 3 digits of
[n]the field to load (3 digits).[w][e]

[dlg SpawnMenuName]
NPC Options[w][e]

[sel SpawnMenu]
Back[f 4 26 0 112][e]
Spawn Model[f 4 26 1 113][e]
Animate Model[f 4 26 2 114][e]

[dlg GENERIC_HELP_114]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]main selection page.[e]

[dlg GENERIC_HELP_112]
[s]Input a [clr 9]GMD filename[clr 0][n]to spawn a character model from.[e]

[dlg GENERIC_HELP_113]
[s]Apply field animations[n]to the last NPC you spawned.[e]

[dlg PersonaMenuName]
Persona Options[w][e]

[sel PersonaMenu]
Back[f 4 26 0 117][e]
Add Persona[f 4 26 1 118][e]
Delete Personas[f 4 26 2 119][e]
Add Skill[f 4 26 3 120][e]

[dlg GENERIC_HELP_120]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]Player Options page.[e]

[dlg GENERIC_HELP_117]
[s]Input a Persona's [clr 9]ID[clr 0][n]to add it to your stock.[e]

[dlg GENERIC_HELP_118]
[s]Permanently remove all[n]Personas from your current stock.[e]

[dlg GENERIC_HELP_119]
[s]Choose a party member and[n]the [clr 9]ID[clr 0] of a Skill to add[n]to their current Persona.[e]


[dlg UnitMenuName]
Select Party Member[w][e]

[sel UnitSelect]
Joker[e]
Ryuji[e]
Morgana[e]
Ann[e]
Yusuke[e]
Makoto[e]
Haru[e]
Futaba[e]
Akechi[e]

[sel UnitSelect2]
Ryuji[e]
Morgana[e]
Ann[e]
Yusuke[e]
Makoto[e]
Haru[e]
Futaba[e]
Akechi[e]

[dlg PersonaDelPrompt[Delete Personas]]
This will permanently remove all 
[n]Personas in your stock. Are you sure?[w][e]

[sel PersonaDelSelect]
No[e]
Yes[e]

[dlg UnitPrompt[Add Skill]]
Choose a character to add a skill to
[n]their currently equipped Persona.[w][e]

[dlg SkillPrompt [Add Skill]]
Enter the ID of the skill that you
[n]want to add (3 digits).[w][e]

[dlg PersonaAddPrompt[Add Persona]]
Input the ID of the Persona you
[n]want to add (3 digits).[w][e]

[dlg NPCPrompt [Model Select]]
Set the first (4 digits) of the NPC
[n]model filename you want to load.[w][e]

[dlg NPCPrompt2 [Model Select]]
Set the next (3 digits) of the NPC
[n]model filename you want to load.[w][e]

[dlg NPCPrompt3 [Model Select]]
Set the last (2 digits) of the NPC
[n]model filename you want to load.[w][e]

[dlg GapPrompt [Animation Test]]
Select the GAP ID (3 digits).[w][e]

[dlg GapPrompt2 [Animation Test]]
Select which animation to play (2 digits).[w][e]

[dlg GapPrompt3 [Animation Test]]
Select whether to loop or not.[w][e]

[dlg GapPrompt4 [Animation Test]]
Select the third parameter (2 digits).[w][e]

[dlg GapPrompt5 [Animation Test]]
Select the animation speed (2 digits).
[n]Default is 10.[w][e]

[dlg GapPrompt6 [Animation Test]]
Select the number of seconds to play.[w][e]

[sel SelectionDialogAnimLoop]
Off[e]
On[e]

[dlg CameraPrompt [Camera Mode]]
Use the D-Pad to manipulate the camera.
[n]Press Triangle to quit.
[n](Camera must be locked first!)[w][e]

[dlg SelectBgmDialog [Ultimate DJ TGE]]
Select a bgm to play.[w][e]


[dlg FlagMenuName]
Flag Options[w][e]

[sel FlagMenu]
Back[f 4 26 0 143][e]
HUD Display[f 4 26 1 144][e]
Add Party Members[f 4 26 2 145][e]
Remove Party Members[f 4 26 3 146][e]
Enable Party Editing[f 4 26 4 147][e]
Navigator[f 4 26 5 148][e]
Change Romance Route[f 4 26 6 149][e]
Room Editor[f 4 26 7 150][e]
Manual Input[f 4 26 8 151][e]
Print Enabled Flags[f 4 26 9 152][e]

[dlg GENERIC_HELP_143]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]main selection page.[e]

[dlg GENERIC_HELP_144]
[s]Show or hide the user interface[n]elements, such as the date, time,[n]and mission list.[e]

[dlg GENERIC_HELP_145]
[s]Make a Persona user available to[n]add to your party.[e]

[dlg GENERIC_HELP_146]
[s]Revoke a Persona user's[n]availability to be added[n]to your party.[e]

[dlg GENERIC_HELP_147]
[s]Allow choosing your own[n]party members from the Stats[n]menu in the pause menu.[e]

[dlg GENERIC_HELP_148]
[s]Change which character[n]currently serves as the Navigator.[e]

[dlg GENERIC_HELP_149]
[s]Start or end a relationship with[n]a female Confidant.[e]

[dlg GENERIC_HELP_150]
[s]Modify the state of the[n]protagonist's bedroom in[n]the Leblanc attic.[e]

[dlg GENERIC_HELP_151]
[s]Enter an 4-digit decimal value[n]of a bit to either[n]enable or disable it.[e]

[dlg GENERIC_HELP_152]
[s]Print all currently enabled[n]bit flag values to the[n]TTY log.[e]

[dlg FieldMenuName]
Field Select[e]

[sel FieldMenu]
Exit[f 4 26 0 155][e]
Enter Field ID[f 4 26 1 156][e]
Load Field[f 4 26 2 157][e]

[dlg GENERIC_HELP_157]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]main selection page.[e]

[dlg GENERIC_HELP_155]
[s]Input the 6 digits of a[n][clr 9]field pack's[clr 0] filename[n](found in ps3.cpk/field)[e]

[dlg GENERIC_HELP_156]
[s]Attempt to load the selected[n]field. [clr 9]WARNING: Some fields may[n]softlock the game.[clr 0][e]

[dlg EventMenuName]
Event Select[e]

[sel EventMenu]
Exit[f 4 26 0 160][e]
Enter Event ID[f 4 26 1 161][e]
Load Event[f 4 26 2 162][e]

[dlg GENERIC_HELP_162]
[s]Return to the [clr 1]Mod Menu's[clr 0][n]main selection page.[e]

[dlg GENERIC_HELP_160]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](found in data.cpk/event)[e]

[dlg GENERIC_HELP_161]
[s]Attempt to load the selected[n]event. [clr 9]WARNING: Some events may[n]softlock the game.[clr 0][e]

[dlg NaviMenuName]
Select Navigator[w][e]

[sel NaviMenu]
Back[e]
Morgana[e]
Futaba[e]
None[e]

[sel DateDisplayDlg]
Enable[e]
Disable[e]

[dlg LoveMenuName]
Select Relationship[w][e]

[sel LoveMenu]
Makoto[e]
Haru[e]
Ann[e]
Futaba[e]
Chihiya[e]
Takemi[e]
Kawakami[e]
Ohya[e]
Hifumi[e]

[sel OnOffSel]
On[e]
Off[e]

[dlg AboutDlg[About this menu]]
Created by [clr 1]TGE[clr 0] and [clr 6]ShrineFox[clr 0] using
[n]TGE's [clr 9]AtlusScriptCompiler[clr 0] tool. Check out
[n]https://shrinefox.github.io to learn more![w][e]

[dlg MeleeError]
Sorry, this function doesn't work yet!
[n]We're missing the offset for these
[n]types of items at the moment.[w][e]

[sel RoomEdit]
Back[e]
Furniture[e]
Collectables[e]
Cleanliness[e]

[sel FurnEdit]
Back[e]
Plant[e]
Sayuri[e]
DVD Player[e]
Game Console[e]
Old TV Set[e]
Radio[e]
Cat Bed[e]
UFO Game Prizes...[e]

[sel CollEdit]
Back[e]
Swan Boat[e]
Ramen[e]
Pennant[e]
Statue[e]
Sky Tree[e]
Big Hera[e]
Shumai[e]
Fusen[e]
I Love[e]
Idol[e]
More...[e]

[sel CollEdit2]
Back[e]
Seiza[e]
Syogi[e]
Hero[e]
Hamaya[e]
Jyainyan[e]
Sushi[e]
Choco[e]
Kumade[e]

[sel CleanEdit]
Back[e]
Bookshelf[e]
Workbench[e]
Visitor Table[e]
Training Chair[e]
Winter Heater[e]
Laptop[e]

[dlg MonthMenuName]
Select a Month[e]

[sel MonthMenu]
January[e]
February[e]
March[e]
April[e]
May[e]
June[e]
July[e]
August[e]
September[e]
October[e]
November[e]
December[e]

[dlg CalendarError]
Invalid day selected.[n]
Please try again.[w][e]

[dlg SelectBossName]
Boss Event Select[w][e]

[sel SelectBoss]
D00_SCENARIO_BATTLE_01[e]
D01_01_SCENARIO_BATTLE_01[e]
D01_01_MORUGANA_BATTLE[e]
D01_02_SCENARIO_BATTLE_01[e]
Previous[e]
Next[e]
[sel SelectBoss1]
D01_03_SCENARIO_BATTLE[e]
D01_01_SUB_BATTLE_01[e]
D01_01_SUB_BATTLE_02[e]
D01_02_GUN_BATTLE[e]
Previous[e]
Next[e]
[sel SelectBoss2]
D01_02_HOLDUP_BATTLE[e]
D01_02_AllOut_Attack_BATTLE[e]
D01_03_P_CHANGE_BATTLE[e]
D01_04_GATEKEEPER_01[e]
Previous[e]
Next[e]
[sel SelectBoss3]
D01_04_GATEKEEPER_02[e]
D01_KAMOSIDA_BOSS[e]
D02_GATEKEEPER_01[e]
D02_GATEKEEPER_02[e]
Previous[e]
Next[e]
[sel SelectBoss4]
D02_GATEKEEPER_03[e]
D02_SCENARIO_BATTLE[e]
D02_KATUSHIKA_BOSS[e]
D03_SCENARIO_BATTLE[e]
Previous[e]
Next[e]
[sel SelectBoss5]
D03_GATEKEEPER_01[e]
D03_GATEKEEPER_02[e]
D03_GATEKEEPER_03[e]
D03_GATEKEEPER_04[e]
Previous[e]
Next[e]
[sel SelectBoss6]
D03_GATEKEEPER_05[e]
D03_KANESHIRO_BOSS[e]
D04_CAIRO_BOSS[e]
D04_GATEKEEPER_01[e]
Previous[e]
Next[e]
[sel SelectBoss7]
D04_GATEKEEPER_02[e]
D04_GATEKEEPER_03[e]
D04_GATEKEEPER_04[e]
D04_FUTABA_BOSS[e]
Previous[e]
Next[e]
[sel SelectBoss8]
D05_FIANCE_BAT[e]
D05_GATEKEEPER_01[e]
D05_GATEKEEPER_02[e]
D05_GATEKEEPER_03[e]
Previous[e]
Next[e]
[sel SelectBoss9]
D05_GATEKEEPER_04[e]
D05_OKUMURA_BOSS[e]
D06_GATEKEEPER_01[e]
D06_GATEKEEPER_02[e]
Previous[e]
Next[e]
[sel SelectBoss10]
D06_GATEKEEPER_157_05_B[e]
D06_GATEKEEPER_157_05_BOSS[e]
D06_AKECHI_FIRST_BATTLE[e]
D06_GATEKEEPER_DARKZONE_BOSS[e]
Previous[e]
Next[e]
[sel SelectBoss11]
D03_GATEKEEPER_CAMERA[e]
D06_GATEKEEPER_DICE_BOSS[e]
D06_SLOT_ENYRY_BATTLE[e]
D06_ESCAPE_BATTLE_01[e]
Previous[e]
Next[e]
[sel SelectBoss12]
D06_SAE_BOSS[e]
D07_GATEKEEPER_01[e]
D07_GATEKEEPER_02[e]
D07_GATEKEEPER_03[e]
Previous[e]
Next[e]
[sel SelectBoss13]
D07_GATEKEEPER_04[e]
D07_TARGET_A[e]
D07_TARGET_B[e]
D07_TARGET_C[e]
Previous[e]
Next[e]
[sel SelectBoss14]
D07_TARGET_D[e]
D07_TARGET_E[e]
D07_AKECHI_BOSS[e]
D07_SHIDO_BOSS[e]
Previous[e]
Next[e]
[sel SelectBoss15]
D08_BOSS_GATE_KEEPER_01[e]
D08_BOSS_GATE_KEEPER_02[e]
D08_BOSS_KEY_GUARD[e]
D08_BOSS_BATTLE[e]
Previous[e]
Next[e]
[sel SelectBoss16]
D08_VELVET_SCENARIO_BAT[e]
D08_LAST_GATEKEEPER_01[e]
D08_LAST_GATEKEEPER_02[e]
D08_LAST_GATEKEEPER_03[e]
Previous[e]
Next[e]
[sel SelectBoss17]
D08_LAST_GATEKEEPER_04[e]
D08_LAST_BOSS_BATTLE[e]
D00_QUEST_BATTLE[e]
D00_YUSUKE_COOP_BATTLE[e]
Previous[e]
Next[e]
[sel SelectBoss18]
int_CLEAR[e]
ALERT_CLEAR_EX[e]
PALACE_CLEAR_SYS[e]
PALACE_CALL_CALENDAR[e]
Previous[e]
Next[e]
[sel SelectBoss19]
SYMBOL_ENCOUNT_START[e]
D_ENCOUNT_START[e]
dungeon_return_calendar[e]
dungeon_return[e]
Previous[e]
Next[e]
[sel SelectBoss20]
dungeon_exit_time_set[e]
dungeon_start_format[e]
DUNGEON_START_SAVE[e]
result_counter_clear[e]
Previous[e]
Next[e]
[sel SelectBoss21]
MVP_CHOICE[e]
D_ENCOUNT_NO_GET[e]
Dummy[e]
Dummy[e]
Previous[e]
Next[e]

[dlg HudTest1]
HUD has been enabled.[w][e]

[dlg HudTest2]
HUD has been disabled.[w][e]

[dlg PersonaAdded]
The chosen Persona has been[n]added to your stock.[w][e]

[dlg PersonaDeleted]
All Personas have been deleted.[w][e]

[dlg WeatherChanged]
Weather has been changed.[w][e]

[dlg LoadCheckError]
Set the required parameters[n]before attempting to load![w][e]

[dlg WeatherMenuName]
Weather Select[w][e]

[sel WeatherMenu]
Back[e]
Sunny[e]
Rainy[e]
Cloudy[e]
Snow[e]
Rainy Season[e]
Typhoon Warning[e]
Sunny Pollen Warning[e]
Cloudy Pollen Warning[e]
Torrential Rain[e]
Sunny Heatwave/Hot Night[e]
Sunny Flu Season[e]
Cloudy Flu Season[e]
