[msg NPC]
[w][e]

[dlg Title_SpawnNPCs]
Spawn NPCs[w][e]

[sel Options_SpawnNPCs]
Spawn Model[ref 0 2][e]
Animate Model[ref 1 3][e]
Set Model Scale[ref 2 4][e]
Attach Item Model[ref 3 5][e]
Spawn Object Model[ref 4 6][e]

[dlg GENERIC_HELP_2]
Input a [clr 9]GMD filename[clr 0]
[n]to spawn a character model from.[e]

[dlg GENERIC_HELP_3]
Apply field animations
[n]to the last NPC you spawned.[e]

[dlg GENERIC_HELP_4]
Set the scale of the[n]NPC model.[e]

[dlg GENERIC_HELP_5]
Input a [clr 9]GMD filename[clr 0]
[n]to attach to the NPC.[e]

[dlg GENERIC_HELP_6]
Input a [clr 9]GMD filename[clr 0]
[n]of an object to spawn.[e]

[dlg Message_SpawnNPC_First]
Set the first (4 digits) of the NPC
[n]filename to load. (Press [clr 2]○[clr 0] to end)[w][e]

[dlg Message_SpawnNPC_Middle]
Set the next (3 digits) of the NPC
[n]model filename to load. (Press [clr 2]○[clr 0] to end)[w][e]

[dlg Message_SpawnNPC_Last]
Set the last (2 digits) of the NPC
[n]model filename to load. (Press [clr 2]○[clr 0] to end)[w][e]

[dlg Message_NPCItem_First]
Enter the first half of the model's
[n]ID from data.cpk/model/item.
[n](Max 4 digits, press [clr 2]○[clr 0] to end).[w][e]

[dlg Message_NPCItem_Last]
Enter the last half of the model's
[n]ID from data.cpk/model/item.
[n](Max 3 digits, press [clr 2]○[clr 0] to end).[w][e]

[dlg Message_NPCObject_First]
Enter the first half of the
[n]model's ID from data.cpk/model/field_tex/object.
[n](Max 3 digits, press [clr 2]○[clr 0] to end).[w][e]

[dlg Message_NPCObject_Last]
Enter the last half of the
[n]model's ID from data.cpk/model/field_tex/object.
[n](Max 3 digits, press [clr 2]○[clr 0] to end).[w][e]

[dlg Message_NPCScale]
Set the character's model scale.
[n](press [clr 2]○[clr 0] to end)
[n]Default is 10.[w][e]