[dlg Title_NPCAnimation]
NPC Animation[w][e]

[sel Options_NPCAnimation]
Set Animation Test .GAP[ref 0 2][e]
Set Test Animation Index[ref 1 3][e]
Toggle Animation Loop[ref 2 4][e]
Set Animation Speed[ref 3 5][e]
Set Animation Time[ref 4 6][e]
Playback Test Animation[ref 5 7][e]

[dlg GENERIC_HELP_2]
Select an NPC's Field [clr 26].GAP[clr 0][n]file to use with the[n]last spawned NPC.[e]

[dlg GENERIC_HELP_3]
Input the index of the[n]animation from the [clr 26].GAP[clr 0][n]that you want to view.[e]

[dlg GENERIC_HELP_4]
Toggle whether you want[n]the animation to repeat or not[n]when it's finished.[e]

[dlg GENERIC_HELP_5]
Choose the playback speed[n]of the animation.[e]

[dlg GENERIC_HELP_6]
Choose how many seconds you[n]would like to play the[n]animation for.[e]

[dlg GENERIC_HELP_7]
Execute the animation playback[n][clr 9]after the above settings[clr 0][n]have been completed.[e]

[dlg Message_FirstNPCGAPDigits [GAP Select]]
Set the first (4 digits) of the
[n]NPC .GAP to load. ([clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_LastNPCGAPDigits [GAP Select]]
Set the last (3 digits) of the
[n]NPC .GAP to load. ([clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_NPCGapID]
Select the .GAP ID.
[n](3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_NPCGapAnimIndex]
Select which animation to play.
[n](2 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_NPCGapLoop]
Select whether to loop[n]the animation or not.[w][e]

[dlg Message_NPCGapSpeed]
Select the animation speed. Default is 10.
[n]([clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_NPCGapTime [Animation Test]]
Select the number of seconds to play.[w][e]
[n](2 digits, [clr 2]○ button[clr 0] to end)[w][e]