[dlg Title_Particles]
Spawn Particle[w][e]

[sel Options_Particles]
Automatic Particle Selection[ref 0 2][e]
Manual Particle Selection[ref 1 3][e]
Set Params to Default[ref 2 4][e]
Set Effect Size[ref 3 5][e]
Set Effect Speed[ref 4 6][e]
Set Effect Position[ref 5 7][e]
Set Effect Translucency[ref 6 8][e]

[dlg GENERIC_HELP_2]
Preview EPL's placed inside[n]'data.cpk\field\effect\bank'[n][clr 9]MUST BE NAMED fb###.EPL[n]OR THE GAME SOFTLOCKS![clr 0][e]

[dlg GENERIC_HELP_3]
Select a 3-digit number from the[n]effect bank folder [clr 9](fb###.EPL)[n][clr 0]to preview.[e]

[dlg GENERIC_HELP_4]
Reset all properties of[n]the current EPL.[n][e]

[dlg GENERIC_HELP_5]
Set the Size[n]of the current EPL.[n][e]

[dlg GENERIC_HELP_6]
Set the Speed[n]of the current EPL.[n][e]

[dlg GENERIC_HELP_7]
Set the Position[n]of the current EPL to the player.[e]

[dlg GENERIC_HELP_8]
Set the Opacity[n]of the current EPL.[n][e]

[dlg Message_ParticleScale]
Set the particles's scale.[n](press [clr 2]○[clr 0] to end)[n]Default is 10.[w][e]

[dlg Message_ParticleSpeed]
Set the particles's speed.[n](press [clr 2]○[clr 0] to end)[n]Default is 10.[w][e]

[dlg Message_ParticleAlpha]
Set the particles's opacity.[n](press [clr 2]○[clr 0] to end)[n]Default is 10.[w][e]