[dlg Title_Stats]
Select Stat Type...[w][e]

[sel Options_Stats]
Knowledge[ref 0 2][e]
Charm[ref 1 3][e]
Proficiency[ref 2 4][e]
Guts[ref 3 5][e]
Kindness[ref 4 6][e]

[dlg GENERIC_HELP_2]
[s]Increase your [clr 26]Knowledge[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_3]
[s]Increase your [clr 26]Charm[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_4]
[s]Increase your [clr 26]Proficiency[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_5]
[s]Increase your [clr 26]Guts[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_6]
[s]Increase your [clr 26]Kindness[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg Message_StatsPoints]
Add how many points?[n](2 digits, [clr 2]○ button[clr 0] to end)[w][e] 