[dlg Title_Env]
[s]Field Lighting[w][e]

[sel Options_Env]
[s]Set all Scenelights to White[f 4 26 0 2][e]
[s]Print Scenelights to TTY[f 4 26 1 3][e]
[s]Set Ambient Scenelight[f 4 26 2 4][e]
[s]Set Diffuse Scenelight[f 4 26 3 5][e]
[s]Set Specular Scenelight[f 4 26 4 6][e]
[s]Print Current Fog Params to TTY[f 4 26 5 7][e]
[s]Set Near Clip[f 4 26 6 8][e]
[s]Set Far Clip[f 4 26 7 9][e]
[s]Set Fog Hue[f 4 26 8 10][e]
[s]Set Fog Saturation[f 4 26 9 11][e]
[s]Set Fog Lightness[f 4 26 10 12][e]
[s]Set Fog Alpha[f 4 26 11 13][e]

[dlg GENERIC_HELP_2]
[s]Set all Scenelight data on[n]the current field to 255.[e]

[dlg GENERIC_HELP_3]
[s]Print all Scenelight data on[n]the current field to the TTY Log.[e]

[dlg GENERIC_HELP_4]
[s]Set the HSL Values for the[n]
Ambient Scenelight.[e]

[dlg GENERIC_HELP_5]
[s]Set the HSL Values for the[n] Diffuse Scenelight.[e]

[dlg GENERIC_HELP_6]
[s] Set the HSL Values for the[n] Specular Scenelight.[e]

[dlg GENERIC_HELP_7]
[s] Print all fog params on[n] the current field to the TTY Log.[e]

[dlg GENERIC_HELP_8]
[s]Set the starting[n] location for the fog.[e]

[dlg GENERIC_HELP_9]
[s]Set the starting[n] radius for the fog.[e]

[dlg GENERIC_HELP_10]
[s]Set the current fog's Hue.[e]

[dlg GENERIC_HELP_11]
[s]Set the current fog's Saturation.[e]

[dlg GENERIC_HELP_12]
[s]Set the current fog's Lightness.[e]

[dlg GENERIC_HELP_13]
[s]Set the current fog's Opacity.[e]

[dlg Message_Hue]
Set Hue to a 3 digit number. (Max 255)[w][e]

[dlg Message_Sat]
Set Saturation to a 3 digit number. (Max 255)[w][e]

[dlg Message_Lum]
Set Lightness to a 3 digit number. (Max 255)[w][e]

[dlg Message_Alp]
Set Opacity to a 3 digit number. (Max 255)[w][e]

[dlg Message_NearClip]
Set the fog's Near Clip[n](press Circle to end)[w][e]

[dlg Message_FarClip]
Set the fog's Far Clip[n](press Circle to end)[w][e]