[dlg Title_FontTest]
Font Test[w][e]

[sel Options_FontTest]
[s]Sample Text[f 4 26 0 2][e]
[s]Uppercase[f 4 26 1 3][e]
[s]Lowercase[f 4 26 2 4][e]
[s]Symbols[f 4 26 3 5][e]
[s]All-in-One[f 4 26 4 6][e]

[dlg GENERIC_HELP_2]
[s]Print a sample sentence[n]for font testing.[e]

[dlg GENERIC_HELP_3]
[s]Print a text message with[n]uppercase letters.[e]

[dlg GENERIC_HELP_4]
[s]Print a text message with[n]lowercase letters.[e]

[dlg GENERIC_HELP_5]
[s]Print a text message with[n]numbers and special[n]characters.[e]

[dlg GENERIC_HELP_6]
[s]Print a text message with[n]all the characters.[e]

[dlg Message_FontTest_Sample [The Font Guy]]
[s]The quick brown fox jumps over[n]the lazy dog. 1234567890[w][e]

[dlg Message_FontTest_Upper [The Font Guy]]
[s]ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]A B C D E F G H I J K L M N O P Q R S T U V W X Y Z[w][e]

[dlg Message_FontTest_Lower [The Font Guy]]
[s]abcdefghijklmnopqrstuvwxyz[n]a b c d e f g h i j k l m n o p q r s t u v w x y z[w][e]

[dlg Message_FontTest_Symbols [The Font Guy]]
[s]1234567890 - _.:,;| !"#$%&/()=?+*{}^\<>`~'@[w][e]

[dlg Message_FontTest_All [The Font Guy]]
[s]ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]abcdefghijklmnopqrstuvwxyz[n]1234567890 - _.:,;| !"#$%&/()=?+*{}^\<>`~'@[w][e]