[dlg Title_PlayerAppearance]
Player Appearance[w][e]

[sel Options_PlayerAppearance]
[s]Set Joker Model[ref 0 2][e]
[s]Set Joker GAP[ref 1 3][e]
[s]Toggle Bag[ref 2 4][e]
[s]Toggle Morgana[ref 3 5][e]
[s]Toggle Umbrella[ref 4 6][e]

[dlg GENERIC_HELP_2]
[s]Select one of the protagonist's[n]GMD models to use[n]in the field.[e]

[dlg GENERIC_HELP_3]
[s]Select one of the protagonist's[n]Field GAP files to use[n]in the field.[e]

[dlg GENERIC_HELP_4]
[s]Show or hide the[n]protagonist's tote bag.[e]

[dlg GENERIC_HELP_5]
[s]Show or hide Morgana[n]in the protagonist's[n]tote bag.[e]

[dlg GENERIC_HELP_6]
[s]Show or hide the[n]protagonist's umbrella.[e]

[dlg Message_PlayerBag]
[s]Show or hide the protagonist's[n]tote bag?[e]

[dlg Message_Morgana]
[s]Show or hide Morgana from the[n]protagonist's tote bag?[e]

[dlg Message_Umbrella]
[s]Show or hide the protagonist's[n]umbrella?[e]