[msg MapFlags]
[w][e]

[dlg Title_MapFlags]
Map Flags[w][e]

[sel Options_MapFlags]
Unset Tired Status[ref 0 3][e]
Set Hideout[ref 1 4][e]
Enable Fast Travel[ref 2 5][e]
Enable Hangout Spots[ref 3 6][e]
Enable Going Out At Night[ref 4 7][e]
Enable Thieves Den[ref 5 8][e] // Royal

[dlg GENERIC_HELP_3]
Make it so you can do
[n]another activity before 
[n]going to sleep.[e]

[dlg GENERIC_HELP_4]
Choose location where you
[n]meet up with party
[n]members for mission.[e]

[dlg GENERIC_HELP_5]
Turn on the ability to
[n]view the Fast Travel
[n]menu.[e]

[dlg GENERIC_HELP_6]
Turn on the ability to
[n]travel to any Confidant
[n]hangout spot.[e]

[dlg GENERIC_HELP_7]
Turn on the ability to
[n]explore the city at
[n]nighttime.[e]

[dlg GENERIC_HELP_8]
Enable the ability to
[n]enter the Thieves Den.[e]

[dlg Title_Hideout]
Set Hideout[w][e]

[sel Options_Hideout]
School Rooftop[e]
Shibuya Walkway[e]
Leblanc 2nd Floor[e]
Leblanc 1st Floor[e]