[msg Spawn]
[w][e]

[dlg Title_Spawn]
Spawn Menu[w][e]

[sel Options_Spawn]
NPC Model[ref 0 2][e]
Field Model[ref 1 3][e]
Particle Effect[ref 2 4][e]

[dlg GENERIC_HELP_2]
Input a [clr 9].GMD filename[clr 0]
[n]to spawn a character model from.[e]

[dlg GENERIC_HELP_3]
Load an item/object model
[n]at Joker's current
[n]coordinates.[e]

[dlg GENERIC_HELP_4]
Load a particle effect from
[n]an EPL Bank at Joker's
[n]current coordinates.[e]