[msg PlayerAppearance]
[w][e]

[dlg Title_PlayerAppearance]
Player Appearance[w][e]

[sel Options_PlayerAppearance]
Set Joker Model[ref 0 2][e]
Set Joker GAP[ref 1 3][e]
Toggle Bag[ref 2 4][e]
Toggle Morgana[ref 3 5][e]
Toggle Umbrella[ref 4 6][e]

[dlg GENERIC_HELP_2]
Select one of the protagonist's
[n]GMD models to use
[n]in the field.[e]

[dlg GENERIC_HELP_3]
Select one of the protagonist's
[n]Field GAP files to use
[n]in the field.[e]

[dlg GENERIC_HELP_4]
Show or hide the
[n]protagonist's tote bag.[e]

[dlg GENERIC_HELP_5]
Show or hide Morgana
[n]in the protagonist's
[n]tote bag.[e]

[dlg GENERIC_HELP_6]
Show or hide the
[n]protagonist's umbrella.[e]

[dlg Message_PlayerBag]
Show or hide the protagonist's
[n]tote bag?[e]

[dlg Message_Morgana]
Show or hide Morgana from the
[n]protagonist's tote bag?[e]

[dlg Message_Umbrella]
Show or hide the protagonist's
[n]umbrella?[e]