[msg Personas]
[w][e]

[dlg Title_Personas]
Personas[w][e]

[sel Options_Personas]
Add Persona[ref 0 2][e]
Delete Personas[ref 1 3][e]
Unlock Full Compendium[ref 2 4][e]
Evolve Persona[ref 3 5][e]

[dlg GENERIC_HELP_2]
Input a Persona's name or ID
[n]to add it to your stock.[e]

[dlg GENERIC_HELP_3]
Permanently remove all Personas
[n]from your current stock.[e]

[dlg GENERIC_HELP_4]
Register every Persona in
[n]the game by filling your
[n]stock with them all.[e]

[dlg GENERIC_HELP_5]
Evolve a party member's Persona
[n]into its Ultimate form.[e]

[dlg Title_AddPersonas]
Add Personas[w][e]

[sel Options_AddPersonas]
Add Persona (Alphabetical)[e]
Add Persona (Reserves)[e]
Add Persona (Manual Input)[e]

[dlg Message_AddPersonaByID]
Input the ID of the Persona to add.
[n](3 digits, press [clr 2]back[clr 0] to end)[w][e]

[dlg Message_PersonaAdded]
The Persona [clr 1][var 0][clr 0] was
[n]added to your stock.[w][e]

[dlg Message_DeleteAllPersonas]
This will permanently remove all 
[n]Personas in your stock.
[n]Are you sure?[w][e]

[dlg Message_PersonasDeleted]
All Personas have been deleted.[w][e]

[dlg Title_PersonaID]
Persona ID (3 Digits)[w][e]