[dlg Title_Events]
Call Event[w][e]

[sel Options_Events]
Enter Event ID[f 4 26 0 2][e]
Load Event[f 4 26 1 3][e]
Enter KeyFree Event ID[f 4 26 2 4][e]
Load KeyFree Event[f 4 26 3 5][e]

[dlg GENERIC_HELP_2]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](dataR.cpk/event)[e]

[dlg GENERIC_HELP_4]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](ps4R.cpk/field).[clr 0][e]

[dlg Message_EventID_Major]
Choose the first 3 digits of
[n]the Event to load.
[n](3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_EventID_Minor [Event Select]]
Choose the last 3 digits of
[n]the Event to load.
[n](3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_KFEventID_Minor [KeyFree Event Select]]
Choose the first 3 digits of
[n]the KeyFree Event to load.
[n](3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_KFEventID_Major [KeyFree Event Select]]
Choose the last 3 digits of
[n]the KeyFree Event to load.
[n](3 digits, [clr 2]○ button[clr 0] to end)[w][e]