[msg PlayerAnimation]
[w][e]

[dlg Title_PlayerAnimation]
Player Animation[w][e]

[sel Options_PlayerAnimation]
Set Joker Field .GAP[ref 0 2][e]
Set Animation Test GAP[ref 1 3][e]
Set Test Animation Index[ref 2 4][e]
Toggle Animation Loop[ref 3 5][e]
Set Animation Speed[ref 4 6][e]
Set Animation Time[ref 5 7][e]
Playback Test Animation[ref 6 8][e]

[dlg GENERIC_HELP_2]
Select one of the protagonist's
[n]Field [clr 26].GAP[clr 0] files to use
[n]in the field. (Starts with [clr 9]bf[clr 0])[e]

[dlg GENERIC_HELP_3]
Input the filename of
[n]a [clr 9]field [clr 26].GAP[clr 0] file for[clr 0]
[n]this character. (Starts with [clr 9]af[clr 0])[e]

[dlg GENERIC_HELP_4]
Input the index of the
[n]animation from the [clr 26].GAP[clr 0]
[n]that you want to view.[e]

[dlg GENERIC_HELP_5]
Toggle whether you want
[n]the animation to repeat or not
[n]when it's finished.[e]

[dlg GENERIC_HELP_6]
Choose the playback speed
[n]of the animation.[e]

[dlg GENERIC_HELP_7]
Choose how many seconds you
[n]would like to play the
[n]animation for.[e]

[dlg GENERIC_HELP_8]
Execute the animation playback
[n][clr 9]after the above settings[clr 0]
[n]have been completed.[e]

[dlg Message_LastGAPDigits [GAP Select]]
Set the last (3 digits) of the
[n]Joker field GAP to load. ([clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_GapID]
Select the GAP ID.
[n](max. 3 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_GapAnimIndex]
Select which animation to play.
[n](max. 2 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_GapLoop]
Select whether to loop
[n]the animation or not.[w][e]

[dlg Message_GapSpeed]
Select the animation speed. Default is 10.
[n]([clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_GapTime [Animation Test]]
Select the number of seconds to play.[w][e]
[n](max. 2 digits, [clr 2]○ button[clr 0] to end)[w][e]