[msg D00_01_e100_101_mes01 [Boyish Voice]]
[s][vp 1 0 0 6 0 0]Good. Now get running![n][w][e]

[msg D00_01_e100_101_mes02 [Boy's Voice]]
[s][vp 1 0 0 12 0 0]This is our only chance![n][w][e]

[msg D00_01_e100_101_mes03 [Girl's Voice]]
[s][vp 1 0 0 13 0 0]Stay calm![n]You can get away now![n][w][e]

[msg D00_01_e100_101_mes04 [Girl's Voice]]
[s][vp 1 0 0 4 0 0]We'll retrieve the[n]briefcase on our end.[n][w][e]

[msg D00_01_e100_101_mes05 [Mysterious Transmission]]
[s][vp 1 0 0 7 0 0]...suspects...not...confirmed...[n]...hold...your...positions...[n][w][e]

[msg D00_01_e100_101_mes06 [Girl's Voice]]
[s][vp 1 0 0 14 0 0]Hm...? What was that...?[n][w][e]

[msg D00_01_e100_101_mes07 [Boyish Voice]]
[s][vp 1 0 0 8 0 0]Don't worry about us.[n]Just concentrate on getting away![n][w][e]

[msg D06_01_e100_101_mes01 [Morgana]]
[s][bup 0 3 0 -1 0][f 4 10 -1 0 0][f 4 25 1 -1 0 0][vp 1 0 0 6 0 0]Good. Now get running![n][w][e]

[msg D06_01_e100_101_mes02 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 -1 0 0][f 4 25 1 -1 0 0][vp 1 0 0 12 0 0]This is our only chance![n][w][e]

[msg D06_01_e100_101_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 -1 0 0][f 4 25 1 -1 0 0][vp 1 0 0 13 0 0]Stay calm![n]You can get away now![n][w][e]

[msg D06_01_e100_101_mes04 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 -1 0 0][f 4 25 1 -1 0 0][vp 1 0 0 4 0 0]We'll retrieve the[n]briefcase on our end.[n][w][e]

[msg D06_01_e100_101_mes05 [Mysterious Transmission]]
[s][vp 1 0 0 7 0 0]...suspects...not...confirmed...[n]...hold...your...positions...[n][w][e]

[msg D06_01_e100_101_mes06 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 -1 0 0][f 4 25 1 -1 0 0][vp 1 0 0 14 0 0]Hm...? What was that...?[n][w][e]

[msg D06_01_e100_101_mes07 [Morgana]]
[s][bup 0 3 0 -1 0][f 4 10 -1 0 0][f 4 25 1 -1 0 0][vp 1 0 0 8 0 0]Don't worry about us.[n]Just concentrate on getting away![n][w][e]

[dlg ModMenuEnable]
[s]The [clr 9]Amicitia Mod Menu[clr 0] has now been[n]enabled! Press the Square button to[n]begin. Have fun![w][e]