[msg Utilities]
[w][e]

[sel Options_Digits]
0[e]
1[e]
2[e]
3[e]
4[e]
5[e]
6[e]
7[e]
8[e]
9[e]

[sel Options_DigitsTen]
0[e]
1[e]
2[e]
3[e]
4[e]
5[e]
6[e]
7[e]
8[e]
9[e]
10[e]

[dlg Message_FloatInteger]
Enter the integer portion of the float.
[n](Press [clr 2]back button[clr 0] to end)[w][e]

[dlg Message_FloatFractional]
Enter the fractional portion of the float.
[n](Press [clr 2]back button[clr 0] to end)[w][e]

[sel Options_YesNo]
Yes[e]
No[e]

[sel Options_NoYes]
No[e]
Yes[e]

[sel Options_OnOff]
On[e]
Off[e]

[sel Options_OffOn]
Off[e]
On[e]

[sel Options_ShowHide]
[s]Show[e]
[s]Hide[e]

[sel Options_LoopDont]
[s]Loop[e]
[s]Don't Loop[e]

[dlg Message_ConfirmNumberInput]
Are you sure you want to
[n]enter the number [clr 1][var 0][clr 0]? Incorrect
[n]IDs may softlock the game.[w][e]

[dlg Message_ConfirmFloatInput]
Are you sure you want to
[n]enter the number [clr 1][var 0].[var 1][clr 0]?[w][e]

[dlg Message_ReloadConfirm]
The field needs to be reloaded
[n]for changes to take effect.
[n]Would you like to do this now?[w][e]

[dlg Title_Units]
Choose Party Member[w][e]

[sel Options_Units]
[f 4 2] [f 4 1][e]
[var 2][e]
[var 3][e]
[var 4][e]
[var 5][e]
[var 6][e]
[var 7][e]
[var 8][e]
[var 9][e]
[var 10][e]// Royal

[sel Options_UnitsNoJoker]
[var 2][e]
[var 3][e]
[var 4][e]
[var 5][e]
[var 6][e]
[var 7][e]
[var 8][e]
[var 9][e]
[var 10][e]// Royal

[dlg Title_UnitsNavi]
Choose Navigator[w][e]

[sel Options_UnitsNavi]
[var 3][e]
[var 8][e]
[var 9][e]// Royal

[dlg Title_RomanceMenu]
Toggle Romance Route[w][e]

[sel Options_RomanceMenu]
[var 6][e]
[var 7][e]
[var 4][e]
[var 8][e]
[var 17][e]
[var 21][e]
[var 22][e]
[var 23][e]
[var 25][e]

[dlg Message_ToggleActiveFlag]
Flag [clr 1][var 0][clr 0] set to [clr 13]On[clr 0].
[n]Would you like to turn it
[n]on or off?[w][e]

[dlg Message_ToggleInactiveFlag]
Flag [clr 1][var 0][clr 0] set to [clr 9]Off[clr 0].
[n]Would you like to turn it
[n]on or off?[w][e]

[dlg Msg_FlgEnabled]
Flag [clr 1][var 0][clr 0] set to [clr 13]On[clr 0].[w][e]

[dlg Msg_FlgDisabled]
Flag [clr 1][var 0][clr 0] set to [clr 9]Off[clr 0].[w][e]

[dlg Title_SpawnItemMajor]
Item GMD(First 4 Digits)[w][e]

[dlg Title_SpawnItemMinor]
Item GMD(Last 3 Digits)[w][e]

[dlg Title_SpawnObjMajor]
Object GMD(First 3 Digits)[w][e]

[dlg Title_SpawnObjMinor]
Object GMD(Last 3 Digits)[w][e]