[sel Options_Digits]
0[e]
1[e]
2[e]
3[e]
4[e]
5[e]
6[e]
7[e]
8[e]
9[e]

[sel Options_DigitsTen]
0[e]
1[e]
2[e]
3[e]
4[e]
5[e]
6[e]
7[e]
8[e]
9[e]
10[e]

[dlg Message_FloatInteger]
Enter the integer portion of the float.
[n](Press Circle to end)[w][e]

[dlg Message_FloatFractional]
Enter the fractional portion of the float.
[n](Press Circle to end)[w][e]

[sel Options_YesNo]
Yes[e]
No[e]

[sel Options_NoYes]
No[e]
Yes[e]

[sel Options_OnOff]
On[e]
Off[e]

[sel Options_OffOn]
Off[e]
On[e]

[sel Options_ShowHide]
[s]Show[e]
[s]Hide[e]

[sel Options_LoopDont]
[s]Loop[e]
[s]Don't Loop[e]

[dlg Message_ConfirmNumberInput]
Are you sure you want to
[n]enter the number [clr 1][f 2 4 0][clr 0]? Incorrect
[n]IDs may softlock the game.[w][e]

[dlg Message_ConfirmFloatInput]
Are you sure you want to[n]
enter the number [clr 1][f 2 4 0].[f 2 4 1][clr 0]?[w][e]

[dlg Message_ReloadConfirm]
The field needs to be reloaded
[n]for changes to take effect.
[n]Would you like to do this now?[w][e]

[dlg Title_Units]
Choose Party Member[w][e]

[sel Options_Units]
Joker[e]
[f 2 4 2][e]
[f 2 4 3][e]
[f 2 4 4][e]
[f 2 4 5][e]
[f 2 4 6][e]
[f 2 4 7][e]
[f 2 4 8][e]
[f 2 4 9][e]
[f 2 4 10][e] // Royal

[sel Options_UnitsNoJoker]
[f 2 4 2][e]
[f 2 4 3][e]
[f 2 4 4][e]
[f 2 4 5][e]
[f 2 4 6][e]
[f 2 4 7][e]
[f 2 4 8][e]
[f 2 4 9][e]
[f 2 4 10][e] // Royal

[dlg Title_UnitsNavi]
Choose Navigator[w][e]

[sel Options_UnitsNavi]
[f 2 4 3][e]
[f 2 4 8][e]
[f 2 4 9][e] // Royal

[dlg Title_RomanceMenu]
Toggle Romance Route[w][e]

[sel Options_RomanceMenu]
[f 2 4 6][e]
[f 2 4 7][e]
[f 2 4 4][e]
[f 2 4 8][e]
[f 2 4 17][e]
[f 2 4 21][e]
[f 2 4 22][e]
[f 2 4 23][e]
[f 2 4 25][e]

[dlg Message_ToggleActiveFlag]
Flag[clr 1][f 2 4 0][clr 0] is [clr 13]On[clr 0].
[n]Would you like to turn it
[n]on or off?[w][e]

[dlg Message_ToggleInactiveFlag]
Flag[clr 1][f 2 4 0][clr 0] is [clr 9]Off[clr 0].
[n]Would you like to turn it
[n]on or off?[w] [e] 