[msg PartyFlags]
[w][e]

[dlg Title_PartyFlags]
Party Flags[w][e]

[sel Options_PartyFlags]
Toggle Party Member Unlocked[ref 0 2][e]
Toggle Party Editing[ref 1 3][e]
Set Navigator[ref 2 4][e]
Toggle Party Follower[ref 3 5][e]
Toggle Baton Pass[ref 4 6][e]
Toggle Black Mask Akechi[ref 5 7][e]// Royal
Toggle Yoshizawa's Name[ref 6 8][e]// Royal
Toggle Showtime[ref 7 9][e]// Royal

[dlg GENERIC_HELP_2]
Toggle whether a party
[n]member is unlocked.[e]

[dlg GENERIC_HELP_3]
Toggle whether you can
[n]add and remove party
[n]members via Stats menu.[e]

[dlg GENERIC_HELP_4]
Choose which character should
[n]serve as the Navigator.[e]

[dlg GENERIC_HELP_5]
Choose which party member
[n]NPCs should follow you in
[n]the dungeon.[e]

[dlg GENERIC_HELP_6]
Toggle whether a party
[n]member can use Baton
[n]Pass in battle.[e]

[dlg GENERIC_HELP_7]
Toggle Akechi's appearance
[n]in battle.[e]

[dlg GENERIC_HELP_8]
Toggle Yoshizawa's name
[n]and appearance as
[n]Sumire.[e]

[dlg GENERIC_HELP_9]
Toggle whether a party
[n]member can use Showtime
[n]in battle.[e]

[dlg Message_BlackMaskActive]
Black Mask Akechi is already active.
[n]Want to revert his appearance?
[n]This won't revert Persona/Skills.[w][e]

[dlg Message_BlackMaskInactive]
Black Mask Akechi has been activated.
[n]Want to also update his Personas
[n]and Skills to 3rd Semester?[w][e]

[dlg Title_BatonRank]
Baton Pass Rank[w][e]

[sel Options_BatonRank]
0[e]
1[e]
2[e]
3[e]
4[e]

[dlg Title_Showtime]
Toggle Showtime[w][e]

[sel Options_Showtime]
Ann/Morgana[e]
Morgana/Haru[e]
Ann/Yusuke[e]
Ryuji/Yusuke[e]
Ryuji/Makoto[e]
Joker/Akechi[e]
Makoto/Haru[e]
Joker/Kasumi[e]

[dlg Message_EnablePartyEdit]
Turn party editing from the Stats[n]
menu on or off?[w][e]