[msg HUDFlags]
[w][e]

[dlg Title_HUDFlags]
HUD Flags[w][e]

[sel Options_HUDFlags]
Toggle HUD[ref 0 2][e]
Invert HUD[ref 1 3][e]

[dlg GENERIC_HELP_2]
Toggle the date, weather,
[n]and mission list on
[n]or off.[e]

[dlg GENERIC_HELP_3]
Toggle inverting the
[n]colors of the calendar
[n]display.[e]

[dlg Message_ToggleHUD]
Would you like to show or
[n]hide the date, weather, and
[n]mission list?[w][e]

[dlg Message_InvertHUD]
Would you like to invert
[n]the colors of the
[n]calendar display?[w][e]