[dlg Title_Player]
Player[w][e]

[sel Options_Player]
[s]Set Joker Appearance[ref 0 2][e]
[s]Set Joker Name[ref 1 3][e]
[s]Set Team Name[ref 2 4][e]
[s]Add Money[ref 3 5][e]
[s]Personas[ref 4 6][e]
[s]Skills[ref 5 7][e]
[s]Items[ref 6 8][e]
[s]Social Stats[ref 7 9][e]
[s]Confidants[ref 8 10][e]

[dlg GENERIC_HELP_2]
[s]Change Joker's field GAP/GMD,[n]attach item models, or[n]preview animations.[n][e]

[dlg GENERIC_HELP_3]
[s]Rename the protagonist at any[n]point in the game.[n][e]

[dlg GENERIC_HELP_4]
[s]Change the group name of the[n]Phantom Thieves at any[n]point in the game.[n][e]

[dlg GENERIC_HELP_5]
[s]Adds a selected amount of yen[n]to your wallet.[e]

[dlg GENERIC_HELP_6]
[s]Adds a selected amount of yen[n]to your wallet.[e]

[dlg GENERIC_HELP_7]
[s]Adds a selected amount of yen[n]to your wallet.[e]

[dlg GENERIC_HELP_8]
[s]Give yourself a desired amount of[n]any consumables, weapons, armor,[n]costumes, or even key items.[e]

[dlg GENERIC_HELP_9]
[s]Add points to your Knowledge,[n]Charm, Proficiency, Guts[n]or Kindness.[e]

[dlg GENERIC_HELP_10]
[s]Select a Confidant and set your[n]current rank with their Arcana.[e]