[msg Player]
[w][e]

[dlg Title_Player]
Player[w][e]

[sel Options_Player]
Set Joker Appearance[ref 0 2][e]
Set Joker Name[ref 1 3][e]
Set Team Name[ref 2 4][e]
Add Money[ref 3 5][e]
Personas[ref 4 6][e]
Skills[ref 5 7][e]
Items[ref 6 8][e]
Social Stats[ref 7 9][e]
Confidants[ref 8 10][e]

[dlg GENERIC_HELP_2]
Change Joker's field GAP/GMD,
[n]attach item models, or
[n]preview animations.[n][e]

[dlg GENERIC_HELP_3]
Rename the protagonist at any
[n]point in the game.[n][e]

[dlg GENERIC_HELP_4]
Change the group name of the
[n]Phantom Thieves at any
[n]point in the game.[n][e]

[dlg GENERIC_HELP_5]
Adds a selected amount of yen
[n]to your wallet.[e]

[dlg GENERIC_HELP_6]
Adds a selected amount of yen
[n]to your wallet.[e]

[dlg GENERIC_HELP_7]
Adds a selected amount of yen
[n]to your wallet.[e]

[dlg GENERIC_HELP_8]
Give yourself a desired amount of
[n]any consumables, weapons, armor,
[n]costumes, or even key items.[e]

[dlg GENERIC_HELP_9]
Add points to your Knowledge,
[n]Charm, Proficiency, Guts
[n]or Kindness.[e]

[dlg GENERIC_HELP_10]
Select a Confidant and set your
[n]current rank with their Arcana.[e]