[msg PlayerModel]
[w][e]

[dlg Title_PlayerModel]
Player Model[w][e]

[sel Options_PlayerModel]
Set Joker Field Model[ref 0 2][e]
Set Joker Model Scale[ref 1 3][e]
Attach Item Model to Joker[ref 2 4][e]

[dlg GENERIC_HELP_2]
Select one of the protagonist's
[n][clr 26].GMD[clr 0] models to use in
[n]the field.[e]

[dlg GENERIC_HELP_3]
Change the scale of Joker's
[n]model (default is 10).[e]

[dlg Title_JokerScale]
Joker Scale (Default: 10)[w][e]

[dlg GENERIC_HELP_4]
Select an item's model ID to
[n]spawn it and connect it to
[n]the character's model.[w][e]

[dlg Title_JokerGMDMiddle]
Joker GMD (Middle 3 Digits)[w][e]

[dlg Title_JokerGMDLast]
Joker GMD (Last 2 Digits)[w][e]

[dlg Message_MiddleDigitsGMD]
Set the middle (3 digits) of the
[n]Joker GMD to load. ([clr 2]back button[clr 0] to end)[w][e]

[dlg Message_LastDigitsGMD]
Set the last (2 digits) of the
[n]Joker GMD to load. ([clr 2]back button[clr 0] to end)[w][e]

[dlg Title_JokerItemMajor]
Item GMD (First 4 Digits)[w][e]

[dlg Title_JokerItemMinor]
Item GMD (Last 3 Digits)[w][e]

[dlg Title_JokerItemBoneID]
Joker Bone ID (3 Digits)[w][e]

[dlg Message_ItemSpawnAttachPlayerMajor]
Enter the first half of the model's[n]ID from /model/item.
[n](4 digits, [clr 2]back button[clr 0] to end).[w][e]

[dlg Message_ItemSpawnAttachPlayerMinor]
Enter the first last of the model's[n]ID from /model/item.
[n](3 digits, [clr 2]back button[clr 0] to end).[w][e]