[msg Camera]
[w][e]

[dlg Title_Camera]
Camera[w][e]

[sel Options_Camera]
Reposition Camera[ref 0 3][e]
Adjust FOV/Zoom[ref 1 4][e]
Unlock Camera[ref 2 5][e]
Lock Camera[ref 3 6][e]
Disable Camera Shake[ref 4 7][e]

[dlg GENERIC_HELP_3]
Move the camera along XYZ axis,
[n]hold buttons to change speed.
[n](Requires controller)//Royal
[e]

[dlg GENERIC_HELP_4]
Adjust the camera's Zoom and
[n]Field of View.
[n](Requires controller)//Royal
[e]

[dlg GENERIC_HELP_5]
Make the camera follow the player
[n]again if previously locked.[e]

[dlg GENERIC_HELP_6]
Makes the camera stationary,
[n]which is required to modify it.[e]