[msg ModMenu]
[w][e]

[msg Title_ModMenu]
Amicitia Mod Menu[w][e]

[sel Options_ModMenu]
Phone/Auto-Recover[ref 0 1][e]
Player[ref 1 2][e]
Teleport[ref 2 3][e]
Call...[ref 3 4][e]
Calendar[ref 4 5][e]
Camera[ref 5 6][e]
Flags[ref 6 7][e]
Spawn[ref 7 8][e]
About[ref 8 9][e]
Royal[ref 9 10][e] // Royal

[dlg GENERIC_HELP_1]
View your IM messages[n]or auto heal the party,
[n]just like the [clr 18]□ button[clr 0]
[n]normally does.[e]

[dlg GENERIC_HELP_2]
Change social stats, items,
[n]Personas, Skills, model,
[n]animations, money or name.[e]

[dlg GENERIC_HELP_3]
Clip through walls and explore
[n] out of bounds areas. Hold
[n][clr 18]□ button[clr 0] to change axis.
[n][clr 9](Controller only or softlock!)[clr 0][e]

[dlg GENERIC_HELP_4]
Call battles, fields, & events,
[n]Cut-ins, particles, calendar,
[n]or sounds by ID.[e]

[dlg GENERIC_HELP_5]
Set a date and time to
[n]travel to, or alter
[n]the weather.[e]

[dlg GENERIC_HELP_6]
Set camera position, FOV,
[n]zoom & rotation, or
[n]modify field lighting.[e]

[dlg GENERIC_HELP_7]
Change various toggles
[n]in the game's memory.[e]

[dlg GENERIC_HELP_8]
Spawn NPCs and preview
[n]their animations, or spawn
[n]or attach item models.[e]

[dlg GENERIC_HELP_9]
Show some info about the
[n]development of this mod.[e]

[dlg GENERIC_HELP_10]
View options exclusive
[n]to Persona 5 Royal.[e]

[dlg Message_About]
[clr 9]Persona 5 Mod Menu[clr 0] by [clr 6]ShrineFox[clr 0]
// Version
[n][clr 1]github.com/Shrinefox/Persona-5-Mod-Menu[clr 0][w][e]
Created using [clr 1]TGE[clr 0]'s [clr 1]Atlus-Script-Tools[clr 0].
[n]github.com/tge-was-taken/Atlus-Script-Tools[w][e]
For more information, visit:
[n][clr 1]shrinefox.com[clr 0][w][e]