[dlg Title_Items]
Select Item Type...[w][e]

[sel Options_Items]
Consumables[ref 0 2][e]
Accessories[ref 1 3][e]
Key Items[ref 2 4][e]
Ranged Weapons[ref 3 5][e]
Melee Weapons[ref 4 6][e]
Outfits[ref 5 7][e]
Armor[ref 6 8][e]
Materials[ref 7 9][e]
Skill Cards[ref 8 10][e]

[dlg GENERIC_HELP_2]
Items that recover HP & SP,[n]relieve status ailments, or[n]provide buffs or debuffs.[e]

[dlg GENERIC_HELP_3]
Items that you can equip to your[n]party members for stat[n]enhancements.[e]

[dlg GENERIC_HELP_4]
Passive items that are acquired[n]throughout the story.[e]

[dlg GENERIC_HELP_5]
Arms that can be equipped to[n]fire bullets during battle.[e]

[dlg GENERIC_HELP_6]
Weapons used for basic physical[n]attacks during battle.[e]

[dlg GENERIC_HELP_7]
Equippable appearance changes[n]for party members that modify[n]their model in the Metaverse.[e]

[dlg GENERIC_HELP_8]
Equippable items that can boost[n]defense or provide other benefits.[e]

[dlg GENERIC_HELP_9]
Items that can be sold to Iwai[n]or used to create tools.[e]

[dlg GENERIC_HELP_10]
Items that can be used to assign[n]Skills to one of your Personas.[e]

[dlg Message_ItemID]
Enter the item ID you want.[n](4 digits, press [clr 2]○[clr 0] to end)[w][e]

[dlg Message_ItemAmount]
Enter how many items you want.[n](2 digits, press [clr 2]○[clr 0] to end)[w][e]