[msg Calendar]
[w][e]

[dlg Title_Calendar]
Calendar[w][e]

[sel Options_Calendar]
Set Next Day[ref 0 2][e]
Go to Next Day[ref 1 3][e]
Set Weather[ref 2 4][e]
Loop Current Day[ref 3 5][e]

[dlg GENERIC_HELP_2]
Choose day & month[n]to warp to.[e]

[dlg GENERIC_HELP_3]
End current day &
[n]warp to the next
[n]specified day.[e]

[dlg GENERIC_HELP_4]
Change the weather
[n]condition. Reload field
[n]to see results.[e]

[dlg GENERIC_HELP_5]
Choose the next time
[n]of day to set after
[n]current day ends.[e]

[dlg Message_CalendarMonth]
Choose what month to start in.
[n]([clr 2]○ button[clr 0] to end)[w][e]

[dlg Title_CalendarMonth]
Select a Month[e]

[sel Options_CalendarMonth]
January[e]
February[e]
March[e]
April[e]
May[e]
June[e]
July[e]
August[e]
September[e]
October[e]
November[e]
December[e]

[dlg Message_CalendarDay]
Choose what day to start on.
[n](2 digits, [clr 2]○ button[clr 0] to end)[w][e]

[dlg Message_CalendarInvalidDay]
Invalid day selected.
[n]Please try again.[w][e]

[dlg Message_CalendarTooFarBack]
You can only go back one day at a time.[w][e]

[dlg Title_Weather]
Weather Select[w][e]

[sel Options_Weather]
Sunny[e]
Rainy[e]
Cloudy[e]
Snow[e]
Rainy Season[e]
Typhoon Warning[e]
Sunny Pollen Warning[e]
Cloudy Pollen Warning[e]
Torrential Rain[e]
Sunny Heatwave/ Hot Night[e]
Sunny Flu Season[e]
Cloudy Flu Season[e]

[dlg Title_Day]
Day (2 Digits)[w][e]