[msg MSG_BLANK]
[s]......[n][w][e]

[msg MND_PHONE_NG_000_00]
[s]I don't have any new messages.[n][w][e]

[msg MSG_TEST_FLD]
[s]Dummy field[n][w][e]

[msg MSG_TEST_DNG]
[s]Dummy field[n][w][e]

[msg MSG_TEST_CELLPHONE_000]
[s]It seems there's no new intel[n]on who may have a Palace...[n][w][e]

[msg MSG_TEST_CELLPHONE_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 -1 0 0]Dummy field[n][w][e]
[s][f 4 10 -1 0 0]Dummy field[n][w][e]

[msg MSG_TEST_CELLPHONE_002 [Ryuji]]
[s][f 5 14]Dummy field[n][w][e]

[msg HELP_MEMENTOS_MISSION_04 [Mission Occurrence!]]
[s][clr 4]Mementos Intel Gained[clr 27][n]Let's send the calling card from the [clr 2]hideout[clr 27].[n]Sometimes, you will gain intel on Mementos from your "[clr 3]teammates[clr 27]" like this.[n][w][e]

[msg MSG_SPOT_AFTERNOON_ERROR]
[s]I should head over to the[n]ticket gates for now...[n][w][e]

[msg MSG_SPOT_NIGHT_ERROR]
[s]I'm feeling pretty tired.[n]I should get to sleep...[n][w][e]

[msg MSG_IN_KF_EVENT]
[s]Now isn't the time to[n]be going somewhere else.[n][w][e]

[msg MSG_IN_KF_EVENT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 -1 0 0]Now's not the time to[n]be heading somewhere else.[n][w][e]

[msg MSG_NG_ROJIURA_OUT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 -1 0 0]Dummy field[n][w][e]
[s][f 4 10 -1 0 0]Dummy field[n][w][e]

[msg MSG_NG_GO_OUT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 -1 0 0]I'm sure you're exhausted.[n]Let's just get to bed.[n][w][e]

[msg MSG_GO_OUT_FRIEND [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 -1 0 0]You really want to go out[n]while you have a friend over?[n][w][e]

[sel SEL_GO_OUT_FRIEND]
[s]Go out[e]
[s]Cancel[e]

[msg MND_CHK_DOOR_playroom]
[s]My teammate has come to hang out though...[n][w][e]

[sel SEL_PC_PLAYROOM_CHK]
[s]Go out[e]
[s]Stay home[e]

[msg MND_MAIL_NG]
[s]I'm too tired today. I should[n]head out another time...[n][w][e]

[msg MND_NG]
[s]Now isn't the time for that...[n][w][e]

[msg MND_SAVE_NG_COMMON]
[s]Now isn't the time for that...[n][w][e]

[msg STOP_OUTDOOR_DEFAULT_MOR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 -1 0 0]We should just head to[n]bed for today, OK?[n][w][e]

[msg STOP_OUTDOOR_DEFAULT]
[s]I should just go to sleep...[n][w][e]

[msg MSG_GO_DUNGEON_TODAY_MOR [Morgana]]
[s][bup 0 3 0 -1 0][f 4 10 -1 0 0]Aren't you exhausted? You[n]should get some rest.[n][w][e]

[msg MND_GO_DUNGEON_TODAY]
[s]I'm tired from going to[n]the Metaverse earlier. I[n]should try and rest...[n][w][e]

[msg MND_GO_SPOT_TODAY]
[s]I'm tired from all the[n]fun I had today. I should[n]try and rest... [n][w][e]

[msg MSG_STOP_NO_DEBUG2 [Morgana]]
[s][bup 0 3 0 -1 0][f 4 10 -1 0 0]Dummy field[n][w][e]

[msg MSG_SAVE_EPISODE_000_00 [Morgana]]
[s][bup 0 3 0 -1 0][f 4 10 -1 0 0][vp 8 2 -1 1163 0 0]Recording your daily activities,[n]huh... Well, I hope people start[n]thinking better of you soon.[n][f 1 3 -1][w][e]

[msg MSG_SAVE_EPISODE_001_00 [Morgana]]
[s][bup 0 3 0 -1 0][f 4 10 -1 0 0][vp 8 2 -1 1025 0 0]Making a record of your[n]daily activities...?[n][f 1 3 -1][w][e]
[s][f 4 10 -1 0 0][vp 8 2 -1 0 0 0]I wish all this hard work you've[n]done to help people would cancel[n]out your criminal history.[n][f 1 3 -1][w][e]

[msg MSG_SAVE_EPISODE_002_00 [Morgana]]
[s][bup 0 3 1 -1 0][f 4 10 -1 0 0][vp 8 2 -1 1187 0 0]Making a record of your daily[n]activities? I hope that comes[n]in handy someday.[n][f 1 3 -1][w][e]

[msg MSG_SAVE_EPISODE_003_00 [Morgana]]
[s][bup 0 3 3 -1 0][f 4 10 -1 0 0][vp 8 2 -1 1178 0 0]Oh, you're making a record[n]of your daily activities...?[n][f 1 3 -1][w][e]
[s][f 4 10 -1 0 0][vp 8 2 -1 0 0 0]I have to say, this world[n]is cruel for treating you[n]like a criminal.[n][f 1 3 -1][w][e]

[msg MSG_SAVE_EPISODE_004_00 [Morgana]]
[s][bup 0 3 0 -1 0][f 4 10 -1 0 0][vp 8 2 -1 1192 0 0]You want to record your[n]daily activities...?[n][f 1 3 -1][w][e]
[s][bup 0 3 1 -1 0][f 4 10 -1 0 0][vp 8 2 -1 0 0 0]Hm, now that I think about it,[n]we've really grown quite a lot.[n][f 1 3 -1][w][e]

[msg MSG_SAVE_EPISODE_005_00 [Morgana]]
[s][bup 0 3 3 -1 0][f 4 10 -1 0 0][vp 8 2 -1 1170 0 0]A record of your daily[n]activities, huh...?[n][f 1 3 -1][w][e]
[s][f 4 10 -1 0 0][vp 8 2 -1 0 0 0]It's a shame your criminal history[n]will never be overwritten...[n][f 1 3 -1][w][e]

[msg MSG_SAVE_EPISODE_006_00 [Morgana]]
[s][bup 0 3 0 -1 0][f 4 10 -1 0 0][vp 8 2 -1 1167 0 0]You're making a record of[n]your daily activities, huh?[n][f 1 3 -1][w][e]
[s][bup 0 3 1 -1 0][f 4 10 -1 0 0][vp 8 2 -1 0 0 0]I wish your criminal slate could[n]get wiped clean in the process...[n][f 1 3 -1][w][e]

