[msg Font]
[w][e]

[dlg Title_FontTest]
Font Test[w][e]

[sel Options_FontTest]
Sample Text[ref 0 2][e]
Uppercase[ref 1 3][e]
Lowercase[ref 2 4][e]
Symbols[ref 3 5][e]
All-in-One[ref 4 6][e]

[dlg GENERIC_HELP_2]
Print a sample sentence
[n]for font testing.[e]

[dlg GENERIC_HELP_3]
Print a text message with
[n]uppercase letters.[e]

[dlg GENERIC_HELP_4]
Print a text message with
[n]lowercase letters.[e]

[dlg GENERIC_HELP_5]
Print a text message with
[n]numbers and special[n]characters.[e]

[dlg GENERIC_HELP_6]
Print a text message with
[n]all the characters.[e]

[dlg Message_FontTest_Sample [The Font Guy]]
The quick brown fox jumps over
[n]the lazy dog. 1234567890[w][e]

[dlg Message_FontTest_Upper [The Font Guy]]
ABCDEFGHIJKLMNOPQRSTUVWXYZ
[n]A B C D E F G H I J K L M N O P Q R S T U V W X Y Z[w][e]

[dlg Message_FontTest_Lower [The Font Guy]]
abcdefghijklmnopqrstuvwxyz
[n]a b c d e f g h i j k l m n o p q r s t u v w x y z[w][e]

[dlg Message_FontTest_Symbols [The Font Guy]]
1234567890 - _.:,;| !"#$%&/()=?+*{}^\<>`~'@[w][e]

[dlg Message_FontTest_All [The Font Guy]]
ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]abcdefghijklmnopqrstuvwxyz
[n]1234567890 - _.:,;| !"#$%&/()=?+*{}^\<>`~'@[w][e]