[msg Royal]
[w][e]

[dlg Title_Royal]
Royal Menu[w][e]

[sel Options_Royal]
Go to Thieves Den[ref 0 3][e]
Change Character[ref 1 4][e]
View Videos[ref 2 5][e]
View Music[ref 3 6][e]
View Gallery[ref 4 7][e]
Play Tycoon[ref 5 8][e]

[dlg GENERIC_HELP_3]
Warp to the Thieves Den when
[n]possible (depends on flags
[n]and the field you're on.)[e]

[dlg GENERIC_HELP_4]
Change character when you're
[n]in the Thieves Den.[e]

[dlg GENERIC_HELP_5]
View Thieves Den Videos menu.[e]

[dlg GENERIC_HELP_6]
View Thieves Den Music menu.[e]

[dlg GENERIC_HELP_7]
View Thieves Den Gallery menu.[e]

[dlg GENERIC_HELP_8]
Begin playing Tycoon minigame.[e]