[msg Call]
[w][e]

[dlg Title_Call]
Call...[w][e]

[sel Options_Call]
Battle[ref 0 2][e]
Field[ref 1 3][e]
Event[ref 2 4][e]
Cut-in[ref 3 5][e]
Font Test[ref 4 6][e]
Sound Test[ref 5 7][e]
Chat[ref 6 8][e]
Shop[ref 7 9][e]

[dlg GENERIC_HELP_2]
Choose a type of battle[n]to start, then begin[n]the fight![e]

[dlg GENERIC_HELP_3]
Enter the ID of a field pack[n]to warp to that map.[e]

[dlg GENERIC_HELP_4]
Enter the ID of an event pack[n]to start the event.[e]

[dlg GENERIC_HELP_5]
Test the dialogue cutins for[n]party members.[e]

[dlg GENERIC_HELP_6]
Test the character placement[n]in the game's font.[e]

[dlg GENERIC_HELP_7]
Select a BGM ID to[n]play back an audio track.[e]

[dlg GENERIC_HELP_8]
Enter the ID of a chat conversation to send to your phone.[e]

[dlg GENERIC_HELP_9]
Enter the ID of a shop to open.[e]