[dlg Title_Call]
Call...[w][e]

[sel Options_Call]
[s]Battle[ref 0 2][e]
[s]Field[ref 1 3][e]
[s]Event[ref 2 4][e]
[s]Cut-in[ref 3 5][e]
[s]Font Test[ref 4 6][e]
[s]Sound Test[ref 5 7][e]

[dlg GENERIC_HELP_2]
[s]Choose a type of battle[n]to start, then begin[n]the fight![e]

[dlg GENERIC_HELP_3]
[s]Enter the ID of a field pack[n]to warp to that map.[e]

[dlg GENERIC_HELP_4]
[s]Enter the ID of an event pack[n]to start the event.[e]

[dlg GENERIC_HELP_5]
[s]Test the dialogue cutins for[n]party members.[e]

[dlg GENERIC_HELP_6]
[s]Test the character placement[n]in the game's font.[e]

[dlg GENERIC_HELP_7]
[s]Select a BGM ID to[n]play back an audio track.[e]