[dlg Title_SoundTest]
Sound Test[w][e]

[sel Options_SoundTest]
[s]Select BGM[f 4 26 0 2][e]
[s]Stop BGM[f 4 26 1 3][e]
[s]Start BGM[f 4 26 2 4][e]

[dlg GENERIC_HELP_2]
[s]Enter a BGM ID to play.[n][e]

[dlg GENERIC_HELP_3]
[s]Stop the currently[n]playing BGM.[e]

[dlg GENERIC_HELP_4]
[s]Fade in the currently[n]selected BGM.[e]

[dlg Message_BGMSelect]
Enter the ID of the BGM
[n]you would like to play.[w][e]