[dlg Title_FieldModels]
Spawn Field Models[w][e]

[sel Options_FieldModels]
Spawn Item Model[ref 0 2][e]
Spawn Object Model[ref 1 3][e]

[dlg GENERIC_HELP_2]
Choose an item model to spawn[n]at Joker's current coordinates.[e]

[dlg GENERIC_HELP_3]
Choose an object model to spawn[n]at Joker's current coordinates.[e]

[dlg Message_ItemSpawnMajor]
Enter the first half of the model's
[n]ID from data.cpk/model/item.
[n](4 digits, [clr 2]○ button[clr 0] to end).[w][e]

[dlg Message_ItemSpawnMinor]
Enter the first last of the model's
[n]ID from data.cpk/model/item.
[n](3 digits, [clr 2]○ button[clr 0] to end).[w][e]

[dlg Message_ObjectSpawnMajor]
Enter the first half of the model's
[n]ID from data.cpk/model/field_tex/object.
[n](4 digits, [clr 2]○ button[clr 0] to end).[w][e]

[dlg Message_ObjectSpawnMinor]
Enter the first last of the model's
[n]ID from data.cpk/model/field_tex/object.
[n](3 digits, [clr 2]○ button[clr 0] to end).[w][e]