[msg Confidants]
[w][e]

[dlg Title_Confidants]
Confidants[w][e]

[sel Options_Confidants]
Set Rank[ref 0 2][e]
Toggle Romance Route[ref 1 3][e]
Set Friendzone Id[ref 2 4][e]

[dlg GENERIC_HELP_2]
Choose a Confidant and
[n]change their current
[n]Rank (0 - 10).[e]

[dlg GENERIC_HELP_3]
Choose a romance-able
[n]Confidant and switch their
[n]romance route on/off.[e]

[dlg GENERIC_HELP_4]
Choose a romance-able
[n]Confidant and switch to their
[n]friendzone arcana Id.[e]

[dlg Title_ConfidantRank]
Set Confidant Rank[w][e]

[sel Options_ConfidantRank]
[ref 0 134]Igor[e]
[ref 1 134][var 3][e]
[ref 2 134][var 6][e]
[ref 3 134][var 7][e]
[ref 4 134][var 5][e]
[ref 5 134][var 16][e]
[ref 6 134][var 4][e]
[ref 7 134][var 2][e]
[ref 8 134][var 9][e]
[ref 9 134][var 8][e]
[ref 10 134][var 17][e]
[ref 11 134][var 19] and [var 18][e]
[ref 12 134][var 20][e]
[ref 13 134][var 21][e]
[ref 14 134][var 22][e]
[ref 15 134][var 23][e]
[ref 16 134][var 24][e]
[ref 17 134][var 25][e]
[ref 18 134][var 26][e]
[ref 19 134][var 27][e]
[ref 20 134][var 28][e]
[ref 21 134][var 10][e]//Royal
[ref 22 134][var 31][e]//Royal

[dlg GENERIC_HELP_0]
Set the Confidant Rank for
[n]the [clr 9]Fool[clr 0] Arcana.[e]

[dlg GENERIC_HELP_1]
Set the Confidant Rank for
[n]the [clr 9]Magician[clr 0] Arcana.[e]

[dlg GENERIC_HELP_2]
Set the Confidant Rank for
[n]the [clr 9]Priestess[clr 0] Arcana.[e]

[dlg GENERIC_HELP_3]
Set the Confidant Rank for
[n]the [clr 9]Empress[clr 0] Arcana.[e]

[dlg GENERIC_HELP_4]
Set the Confidant Rank for
[n]the [clr 9]Emperor[clr 0] Arcana.[e]

[dlg GENERIC_HELP_5]
Set the Confidant Rank for
[n]the [clr 9]Hierophant[clr 0] Arcana.[e]

[dlg GENERIC_HELP_6]
Set the Confidant Rank for
[n]the [clr 9]Lovers[clr 0] Arcana.[e]

[dlg GENERIC_HELP_7]
Set the Confidant Rank for
[n]the [clr 9]Chariot[clr 0] Arcana.[e]

[dlg GENERIC_HELP_8]
Set the Confidant Rank for
[n]the [clr 9]Justice[clr 0] Arcana.[e]

[dlg GENERIC_HELP_9]
Set the Confidant Rank for
[n]the [clr 9]Hermit[clr 0] Arcana.[e]

[dlg GENERIC_HELP_10]
Set the Confidant Rank for
[n]the [clr 9]Fortune[clr 0] Arcana.[e]

[dlg GENERIC_HELP_11]
Set the Confidant Rank for
[n]the [clr 9]Strength[clr 0] Arcana.[e]

[dlg GENERIC_HELP_12]
Set the Confidant Rank for
[n]the [clr 9]Hanged-Man[clr 0] Arcana.[e]

[dlg GENERIC_HELP_13]
Set the Confidant Rank for
[n]the [clr 9]Death[clr 0] Arcana.[e]

[dlg GENERIC_HELP_14]
Set the Confidant Rank for
[n]the [clr 9]Temperance[clr 0] Arcana.[e]

[dlg GENERIC_HELP_15]
Set the Confidant Rank for
[n]the [clr 9]Devil[clr 0] Arcana.[e]

[dlg GENERIC_HELP_16]
Set the Confidant Rank for
[n]the [clr 9]Tower[clr 0] Arcana.[e]

[dlg GENERIC_HELP_17]
Set the Confidant Rank for
[n]the [clr 9]Star[clr 0] Arcana.[e]

[dlg GENERIC_HELP_18]
Set the Confidant Rank for
[n]the [clr 9]Moon[clr 0] Arcana.[e]

[dlg GENERIC_HELP_19]
Set the Confidant Rank for
[n]the [clr 9]Sun[clr 0] Arcana.[e]

[dlg GENERIC_HELP_20]
Set the Confidant Rank for
[n]the [clr 9]Judgement[clr 0] Arcana.[e]

[dlg GENERIC_HELP_21]
Set the Confidant Rank for
[n]the [clr 9]Faith[clr 0] Arcana.[e]

[dlg GENERIC_HELP_22]
Set the Confidant Rank for
[n]the [clr 9]Councillor[clr 0] Arcana.[e]

[dlg Message_ConfidantRank]
Enter the desired Confidant rank.[w][e]

[dlg Title_ConfidantFriend]
Input Confidant Id[w][e]