[msg Confidants]
[w][e]

[dlg Title_Confidants]
Confidants[w][e]

[sel Options_Confidants]
Set Rank[ref 0 2][e]
Toggle Romance Route[ref 1 3][e]

[dlg GENERIC_HELP_2]
Choose a Confidant and
[n]change their current
[n]Rank (0 - 10).[e]

[dlg GENERIC_HELP_3]
Choose a romance-able
[n]Confidant and switch their
[n]romance route on/off.[e]

[dlg Title_ConfidantRank]
Set Confidant Rank[w][e]

[sel Options_ConfidantRank]
Igor[ref 0 134][e]
[f 2 4 3][e]
[f 2 4 6][e]
[f 2 4 7][e]
[f 2 4 5][e]
[f 2 4 16][e]
[f 2 4 4][e]
[f 2 4 2][e]
[f 2 4 9][e]
[f 2 4 8][e]
[f 2 4 17][e]
[f 2 4 19] and [f 2 4 18][e]
[f 2 4 20][e]
[f 2 4 21][e]
[f 2 4 22][e]
[f 2 4 23][e]
[f 2 4 24][e]
[f 2 4 25][e]
[f 2 4 26][e]
[f 2 4 27][e]
[f 2 4 28][e]

[dlg Message_ConfidantRank]
Enter the desired Confidant rank.[w][e]